import type { AppSettings, Payment, Voucher } from "@/types";
import { bi, daysAgo, daysFromNow, hoursAgo } from "./helpers";

export const SEED_SETTINGS: AppSettings = {
  brandName: "TryoutKu",
  tagline: bi(
    "Platform tryout online untuk CPNS, TOEFL, Psikotes & tes umum",
    "Online tryout platform for CPNS, TOEFL, psychometric & general tests",
  ),
  contactEmail: "halo@tryoutku.id",
  contactWhatsapp: "0812-3456-7890",
  website: "https://tryoutku.id",
  defaultLocale: "id",
  timezone: "Asia/Jakarta",
  autoApprovePayments: false,
  maintenanceMode: false,
  paymentMethods: [
    {
      id: "pm-bca",
      kind: "bank",
      name: "Bank BCA",
      accountNumber: "123 456 7890",
      accountName: "PT TryoutKu Indonesia",
      active: true,
      instructions: bi(
        "Transfer tepat sesuai nominal + kode unik agar pembayaran terverifikasi otomatis.",
        "Transfer the exact amount including the unique code so the payment verifies automatically.",
      ),
    },
    {
      id: "pm-bri",
      kind: "bank",
      name: "Bank BRI",
      accountNumber: "0987 654 321",
      accountName: "PT TryoutKu Indonesia",
      active: true,
    },
    {
      id: "pm-bni",
      kind: "bank",
      name: "Bank BNI",
      accountNumber: "555 111 222",
      accountName: "PT TryoutKu Indonesia",
      active: false,
    },
    {
      id: "pm-ewallet",
      kind: "ewallet",
      name: "DANA / OVO / GoPay",
      accountNumber: "0812-3456-7890",
      accountName: "TryoutKu (Andini Lestari)",
      active: true,
    },
    {
      id: "pm-qris",
      kind: "qris",
      name: "QRIS Statis",
      accountNumber: "ID1024315678901",
      accountName: "PT TryoutKu Indonesia",
      qrUrl: "/images/qris-sample.svg",
      active: true,
      instructions: bi(
        "Pindai QRIS dari aplikasi pembayaran apa pun, lalu unggah bukti pembayaran.",
        "Scan the QRIS from any payment app, then upload the payment proof.",
      ),
    },
  ],
};

export const SEED_PAYMENTS: Payment[] = [
  {
    id: "pay-001",
    invoiceCode: "INV-2501-0001",
    userId: "usr-participant",
    packageId: "pkg-umum-1",
    amount: 39_000,
    uniqueCode: 137,
    total: 39_137,
    discount: 0,
    methodId: "pm-bca",
    status: "approved",
    proofUrl: "/images/proof-sample.svg",
    proofFileName: "bukti-bca-39137.png",
    uploadedAt: daysAgo(8),
    createdAt: daysAgo(8),
    expiresAt: daysFromNow(-7),
    verifiedAt: new Date(new Date(daysAgo(8)).getTime() + 7_200_000).toISOString(),
    verifiedBy: "usr-admin",
  },
  {
    id: "pay-002",
    invoiceCode: "INV-2501-0002",
    userId: "usr-participant",
    packageId: "pkg-skd-a",
    amount: 49_000,
    uniqueCode: 214,
    total: 49_214,
    discount: 0,
    methodId: "pm-qris",
    status: "pending",
    proofUrl: "/images/proof-sample.svg",
    proofFileName: "bukti-qris-49214.png",
    uploadedAt: hoursAgo(20),
    createdAt: hoursAgo(21),
    expiresAt: daysFromNow(1),
  },
  {
    id: "pay-003",
    invoiceCode: "INV-2501-0003",
    userId: "usr-participant",
    packageId: "pkg-kecermatan",
    amount: 29_000,
    uniqueCode: 512,
    total: 29_512,
    discount: 0,
    methodId: "pm-ewallet",
    status: "rejected",
    note: "Bukti transfer tidak terbaca (buram). Silakan unggah ulang bukti dengan nominal dan tanggal yang jelas.",
    proofFileName: "bukti-dana-29512.jpg",
    uploadedAt: daysAgo(4),
    createdAt: daysAgo(4),
    expiresAt: daysAgo(3),
    verifiedAt: daysAgo(3),
    verifiedBy: "usr-admin",
  },
  {
    id: "pay-004",
    invoiceCode: "INV-2501-0004",
    userId: "usr-participant-2",
    packageId: "pkg-skd-a",
    amount: 49_000,
    uniqueCode: 388,
    total: 49_388,
    discount: 0,
    voucherCode: "PERKASA10",
    methodId: "pm-bri",
    status: "pending",
    proofFileName: "bukti-bri-49388.png",
    uploadedAt: hoursAgo(3),
    createdAt: hoursAgo(4),
    expiresAt: daysFromNow(1),
  },
  {
    id: "pay-005",
    invoiceCode: "INV-2501-0005",
    userId: "usr-participant-3",
    packageId: "pkg-umum-1",
    amount: 39_000,
    uniqueCode: 741,
    total: 39_741,
    discount: 15_000,
    voucherCode: "DISKON25",
    methodId: "pm-bca",
    status: "approved",
    proofFileName: "bukti-bca-39741.png",
    uploadedAt: daysAgo(2),
    createdAt: daysAgo(2),
    expiresAt: daysFromNow(-1),
    verifiedAt: new Date(new Date(daysAgo(2)).getTime() + 14_400_000).toISOString(),
    verifiedBy: "usr-admin",
  },
];

export const SEED_VOUCHERS: Voucher[] = [
  {
    id: "voc-perkasa10",
    code: "PERKASA10",
    type: "percent",
    value: 10,
    maxDiscount: 10_000,
    minAmount: 29_000,
    usageLimit: 500,
    usedCount: 213,
    validFrom: daysAgo(60),
    validUntil: daysFromNow(30),
    active: true,
    packageIds: [],
    description: bi("Diskon 10% maksimal Rp10.000 untuk semua paket.", "10% off, up to Rp10.000, for every package."),
  },
  {
    id: "voc-diskon25",
    code: "DISKON25",
    type: "amount",
    value: 25_000,
    minAmount: 39_000,
    usageLimit: 100,
    usedCount: 64,
    validFrom: daysAgo(30),
    validUntil: daysFromNow(14),
    active: true,
    packageIds: [],
    description: bi("Potongan langsung Rp25.000 minimal transaksi Rp39.000.", "Flat Rp25.000 off with a minimum spend of Rp39.000."),
  },
  {
    id: "voc-gratis2025",
    code: "GRATIS2025",
    type: "percent",
    value: 100,
    maxDiscount: 59_000,
    usageLimit: 50,
    usedCount: 50,
    validFrom: daysAgo(45),
    validUntil: daysAgo(5),
    active: false,
    packageIds: [],
    description: bi("Kode promo launching (kuota habis).", "Launch promo code (quota used up)."),
  },
  {
    id: "voc-skd-baru",
    code: "SKDBARU",
    type: "amount",
    value: 15_000,
    minAmount: 49_000,
    usageLimit: null,
    usedCount: 12,
    validFrom: daysAgo(10),
    validUntil: daysFromNow(20),
    active: true,
    packageIds: ["pkg-skd-a", "pkg-skd-b"],
    description: bi("Potongan Rp15.000 khusus paket SKD CPNS.", "Rp15.000 off, SKD CPNS packages only."),
  },
];
