import type { ActivityLog } from "@/types";
import { bi, daysAgo, hoursAgo, minutesAgo } from "./helpers";

export const SEED_ACTIVITY_LOGS: ActivityLog[] = [
  {
    id: "log-001",
    userId: "usr-participant",
    userName: "Andini Lestari",
    action: "payment.uploaded",
    targetType: "payment",
    targetId: "pay-002",
    message: bi("mengunggah bukti pembayaran INV-2501-0002", "uploaded payment proof INV-2501-0002"),
    createdAt: hoursAgo(20),
  },
  {
    id: "log-002",
    userId: "usr-admin",
    userName: "Rina Kartika",
    action: "payment.approved",
    targetType: "payment",
    targetId: "pay-005",
    message: bi("menyetujui pembayaran INV-2501-0005", "approved payment INV-2501-0005"),
    createdAt: daysAgo(2),
  },
  {
    id: "log-003",
    userId: "usr-admin",
    userName: "Rina Kartika",
    action: "payment.rejected",
    targetType: "payment",
    targetId: "pay-003",
    message: bi("menolak pembayaran INV-2501-0003", "rejected payment INV-2501-0003"),
    createdAt: daysAgo(3),
  },
  {
    id: "log-004",
    userId: "usr-participant",
    userName: "Andini Lestari",
    action: "attempt.submitted",
    targetType: "attempt",
    targetId: "att-toefl-1",
    message: bi("menyelesaikan TOEFL ITP Mini Test", "completed TOEFL ITP Mini Test"),
    createdAt: daysAgo(2),
  },
  {
    id: "log-005",
    userId: "usr-host",
    userName: "Bagus Pratama, S.Pd.",
    action: "session.created",
    targetType: "session",
    targetId: "ses-live-umum",
    message: bi("membuat sesi live K7X2P9", "created live session K7X2P9"),
    createdAt: hoursAgo(2),
  },
  {
    id: "log-006",
    userId: "usr-admin",
    userName: "Rina Kartika",
    action: "package.published",
    targetType: "package",
    targetId: "pkg-umum-1",
    message: bi("memublikasikan paket Tes Umum: Pengetahuan, Logika & Esai", "published the General Test package"),
    createdAt: daysAgo(6),
  },
  {
    id: "log-007",
    userId: "usr-participant-5",
    userName: "Sekar Ayu Wulandari",
    action: "session.joined",
    targetType: "session",
    targetId: "ses-scheduled-toefl",
    message: bi("bergabung ke sesi TFL24A", "joined session TFL24A"),
    createdAt: hoursAgo(1),
  },
  {
    id: "log-008",
    userId: "usr-participant",
    userName: "Andini Lestari",
    action: "attempt.started",
    targetType: "attempt",
    targetId: "att-umum-1",
    message: bi("memulai Tes Umum: Pengetahuan, Logika & Esai", "started the General Test package"),
    createdAt: minutesAgo(120),
  },
];
