import type { PackageSubtest, TryoutPackage } from "@/types";
import { bi, daysAgo } from "./helpers";
import { TIU_QUESTION_IDS, TKP_QUESTION_IDS, TWK_QUESTION_IDS } from "./questions/skd";
import {
  TOEFL_LISTENING_IDS,
  TOEFL_READING_IDS,
  TOEFL_STRUCTURE_IDS,
} from "./questions/toefl";
import { KEPRIBADIAN_QUESTION_IDS } from "./questions/psikotes";
import { UMUM_ESAI_IDS, UMUM_LOGIKA_IDS, UMUM_PU_IDS } from "./questions/umum";

function sub(order: number, subtestId: string, questionIds: string[], selection?: PackageSubtest["selection"]): PackageSubtest {
  return { order, subtestId, questionIds, selection };
}

const gradient = (from: string, to: string, icon: string) => ({ kind: "gradient" as const, from, to, icon });

export const SEED_PACKAGES: TryoutPackage[] = [
  {
    id: "pkg-skd-a",
    slug: "tryout-skd-cpns-2025-paket-a",
    title: bi("Tryout SKD CPNS 2025 – Paket A", "CPNS SKD Tryout 2025 – Package A"),
    description: bi(
      "Simulasi SKD CPNS lengkap: TWK, TIU, dan TKP dengan timer 100 menit, passing grade resmi, serta pembahasan per soal. Beberapa soal TIU memuat rumus matematika yang ditampilkan dengan KaTeX.",
      "A complete CPNS SKD simulation: TWK, TIU and TKP with a 100 minute timer, official passing grades, and a per-question discussion. Some TIU questions contain math formulas rendered with KaTeX.",
    ),
    categoryId: "cat-skd",
    testTypeId: "tt-skd",
    pricingModel: "freemium",
    price: 49_000,
    discountPrice: 39_000,
    thumbnail: gradient("#4f46e5", "#7c3aed", "Landmark"),
    subtests: [
      sub(1, "st-twk", TWK_QUESTION_IDS),
      sub(2, "st-tiu", TIU_QUESTION_IDS),
      sub(3, "st-tkp", TKP_QUESTION_IDS),
    ],
    durationMinutes: 100,
    totalQuestions: TWK_QUESTION_IDS.length + TIU_QUESTION_IDS.length + TKP_QUESTION_IDS.length,
    difficulty: "medium",
    rating: 4.8,
    ratingCount: 1_248,
    participantCount: 12_480,
    tags: ["cpns", "skd", "twk", "tiu", "tkp", "populer"],
    status: "published",
    publishedAt: daysAgo(24),
    showDiscussion: true,
    allowBack: false,
    shuffleQuestions: true,
    shuffleOptions: true,
    createdBy: "usr-admin",
    createdAt: daysAgo(30),
    updatedAt: daysAgo(24),
  },
  {
    id: "pkg-toefl-mini",
    slug: "toefl-itp-mini-test",
    title: bi("TOEFL ITP Mini Test (Listening + Structure + Reading)", "TOEFL ITP Mini Test (Listening + Structure + Reading)"),
    description: bi(
      "Versi ringkas TOEFL ITP dengan audio listening asli (maksimal 1x putar), soal structure, dan reading berbasis bacaan. Skor dikonversi ke skala 310–677 menggunakan tabel konversi resmi.",
      "A compact TOEFL ITP version with real listening audio (1 play only), structure questions, and passage-based reading. Scores are converted to the 310–677 scale using the official conversion table.",
    ),
    categoryId: "cat-toefl",
    testTypeId: "tt-toefl",
    pricingModel: "free",
    price: 0,
    thumbnail: gradient("#0ea5e9", "#06b6d4", "Languages"),
    subtests: [
      sub(1, "st-toefl-listening", TOEFL_LISTENING_IDS),
      sub(2, "st-toefl-structure", TOEFL_STRUCTURE_IDS),
      sub(3, "st-toefl-reading", TOEFL_READING_IDS),
    ],
    durationMinutes: 50,
    totalQuestions: TOEFL_LISTENING_IDS.length + TOEFL_STRUCTURE_IDS.length + TOEFL_READING_IDS.length,
    difficulty: "medium",
    rating: 4.6,
    ratingCount: 512,
    participantCount: 3_210,
    tags: ["toefl", "bahasa-inggris", "listening", "audio", "gratis"],
    status: "published",
    publishedAt: daysAgo(18),
    showDiscussion: true,
    allowBack: true,
    shuffleQuestions: false,
    shuffleOptions: true,
    createdBy: "usr-admin",
    createdAt: daysAgo(20),
    updatedAt: daysAgo(18),
  },
  {
    id: "pkg-kecermatan",
    slug: "tes-kecermatan-lengkap-3-varian",
    title: bi("Tes Kecermatan Lengkap (3 Varian)", "Complete Accuracy Test (3 Variants)"),
    description: bi(
      "Latihan kecermatan dengan tiga varian: karakter hilang, Kraepelin/Pauli, dan perbandingan angka. Seluruh soal digenerate otomatis dari konfigurasi, lengkap dengan timer per kolom dan analisis kecepatan, ketelitian, serta keajegan.",
      "Accuracy practice in three variants: missing character, Kraepelin/Pauli, and number comparison. All questions are generated from configuration, with per-column timers and speed, accuracy and consistency analytics.",
    ),
    categoryId: "cat-psikotes",
    testTypeId: "tt-psikotes",
    pricingModel: "freemium",
    price: 29_000,
    thumbnail: gradient("#a21caf", "#ec4899", "Brain"),
    subtests: [
      sub(1, "st-kecermatan-karakter", []),
      sub(2, "st-kecermatan-kraepelin", []),
      sub(3, "st-kecermatan-perbandingan", []),
    ],
    durationMinutes: 21,
    totalQuestions: 194,
    difficulty: "hard",
    rating: 4.7,
    ratingCount: 386,
    participantCount: 5_120,
    tags: ["psikotes", "kecermatan", "kraepelin", "generator"],
    status: "published",
    publishedAt: daysAgo(12),
    showDiscussion: false,
    allowBack: false,
    shuffleQuestions: false,
    shuffleOptions: false,
    createdBy: "usr-admin",
    createdAt: daysAgo(14),
    updatedAt: daysAgo(12),
  },
  {
    id: "pkg-kepribadian",
    slug: "tes-kepribadian-big-five",
    title: bi("Tes Kepribadian Big Five", "Big Five Personality Test"),
    description: bi(
      "12 item skala Likert yang dipetakan ke lima dimensi kepribadian: Keterbukaan, Ketelitian, Ekstraversi, Keramahan, dan Stabilitas Emosi. Hasil berupa profil radar, bukan benar/salah.",
      "12 Likert-scale items mapped onto five personality dimensions: Openness, Conscientiousness, Extraversion, Agreeableness and Emotional Stability. The result is a radar profile, not a right/wrong score.",
    ),
    categoryId: "cat-psikotes",
    testTypeId: "tt-psikotes",
    pricingModel: "free",
    price: 0,
    thumbnail: gradient("#6366f1", "#22d3ee", "UserRound"),
    subtests: [sub(1, "st-kepribadian", KEPRIBADIAN_QUESTION_IDS)],
    durationMinutes: 15,
    totalQuestions: KEPRIBADIAN_QUESTION_IDS.length,
    difficulty: "easy",
    rating: 4.5,
    ratingCount: 274,
    participantCount: 2_870,
    tags: ["psikotes", "kepribadian", "likert", "gratis"],
    status: "published",
    publishedAt: daysAgo(9),
    showDiscussion: true,
    allowBack: true,
    shuffleQuestions: true,
    shuffleOptions: false,
    createdBy: "usr-admin",
    createdAt: daysAgo(11),
    updatedAt: daysAgo(9),
  },
  {
    id: "pkg-umum-1",
    slug: "tes-umum-logika-numerik-paket-1",
    title: bi("Tes Umum: Pengetahuan, Logika & Esai", "General Test: Knowledge, Logic & Essay"),
    description: bi(
      "Kombinasi tipe soal lengkap: pilihan ganda, pilihan ganda jamak, benar/salah, menjodohkan, mengurutkan, isian, dan esai yang dinilai manual. Subtes logika menggunakan penalti jawaban salah (-1).",
      "A full mix of question types: single choice, multiple answer, true/false, matching, ordering, fill in the blank, and manually graded essays. The logic subtest penalises wrong answers (-1).",
    ),
    categoryId: "cat-umum",
    testTypeId: "tt-umum",
    pricingModel: "paid",
    price: 39_000,
    thumbnail: gradient("#10b981", "#14b8a6", "ClipboardList"),
    subtests: [
      sub(1, "st-umum-pu", UMUM_PU_IDS),
      sub(2, "st-umum-logika", UMUM_LOGIKA_IDS),
      sub(3, "st-umum-esai", UMUM_ESAI_IDS),
    ],
    durationMinutes: 65,
    totalQuestions: UMUM_PU_IDS.length + UMUM_LOGIKA_IDS.length + UMUM_ESAI_IDS.length,
    difficulty: "medium",
    rating: 4.4,
    ratingCount: 198,
    participantCount: 1_840,
    tags: ["tes-umum", "logika", "esai", "berbayar"],
    status: "published",
    publishedAt: daysAgo(6),
    showDiscussion: true,
    allowBack: true,
    shuffleQuestions: true,
    shuffleOptions: true,
    createdBy: "usr-admin",
    createdAt: daysAgo(8),
    updatedAt: daysAgo(6),
  },
  {
    id: "pkg-skd-b",
    slug: "tryout-skd-cpns-2025-paket-b",
    title: bi("Tryout SKD CPNS 2025 – Paket B (Draft)", "CPNS SKD Tryout 2025 – Package B (Draft)"),
    description: bi(
      "Paket lanjutan dengan komposisi soal berbeda. Masih berstatus draft dan belum dipublikasikan ke katalog.",
      "An advanced package with a different question composition. Still a draft and not published to the catalog.",
    ),
    categoryId: "cat-skd",
    testTypeId: "tt-skd",
    pricingModel: "paid",
    price: 59_000,
    thumbnail: gradient("#f59e0b", "#ef4444", "Landmark"),
    subtests: [sub(1, "st-twk", TWK_QUESTION_IDS), sub(2, "st-tiu", TIU_QUESTION_IDS)],
    durationMinutes: 100,
    totalQuestions: TWK_QUESTION_IDS.length + TIU_QUESTION_IDS.length,
    difficulty: "hard",
    rating: 0,
    ratingCount: 0,
    participantCount: 0,
    tags: ["cpns", "skd", "draft"],
    status: "draft",
    showDiscussion: true,
    allowBack: false,
    shuffleQuestions: true,
    shuffleOptions: true,
    createdBy: "usr-admin",
    createdAt: daysAgo(3),
    updatedAt: daysAgo(3),
  },
];
