import type { Session } from "@/types";
import { bi, daysAgo, hoursAgo, hoursFromNow, minutesAgo } from "./helpers";

export const SEED_SESSIONS: Session[] = [
  {
    id: "ses-live-umum",
    code: "K7X2P9",
    packageId: "pkg-umum-1",
    hostId: "usr-host",
    title: bi("Latihan Tes Umum – Sesi Live", "General Test Practice – Live Session"),
    mode: "live",
    status: "lobby",
    requireLogin: true,
    maxParticipants: 40,
    shuffleQuestions: true,
    shuffleOptions: true,
    showResultsImmediately: false,
    leaderboard: true,
    extraTimeSeconds: 0,
    participants: [
      {
        id: "sp-1",
        sessionId: "ses-live-umum",
        userId: "usr-participant-2",
        name: "Dimas Saputra",
        avatarColor: "#16a34a",
        joinedAt: minutesAgo(12),
        status: "online",
        answered: 4,
        total: 14,
        currentIndex: 4,
        score: 20,
        tabSwitchCount: 0,
      },
      {
        id: "sp-2",
        sessionId: "ses-live-umum",
        userId: "usr-participant-3",
        name: "Nadia Rahmawati",
        avatarColor: "#db2777",
        joinedAt: minutesAgo(9),
        status: "online",
        answered: 6,
        total: 14,
        currentIndex: 6,
        score: 28,
        tabSwitchCount: 1,
      },
      {
        id: "sp-3",
        sessionId: "ses-live-umum",
        userId: "usr-participant-4",
        name: "Fajar Nugroho",
        avatarColor: "#7c3aed",
        joinedAt: minutesAgo(4),
        status: "online",
        answered: 1,
        total: 14,
        currentIndex: 1,
        score: 5,
        tabSwitchCount: 0,
      },
    ],
    createdAt: hoursAgo(2),
  },
  {
    id: "ses-scheduled-toefl",
    code: "TFL24A",
    packageId: "pkg-toefl-mini",
    hostId: "usr-host",
    title: bi("TOEFL Mini Test – Sesi Terjadwal", "TOEFL Mini Test – Scheduled Session"),
    mode: "scheduled",
    status: "lobby",
    requireLogin: false,
    maxParticipants: 100,
    shuffleQuestions: false,
    shuffleOptions: true,
    showResultsImmediately: true,
    leaderboard: true,
    extraTimeSeconds: 0,
    opensAt: hoursFromNow(6),
    closesAt: hoursFromNow(8),
    participants: [
      {
        id: "sp-4",
        sessionId: "ses-scheduled-toefl",
        userId: "usr-participant-5",
        name: "Sekar Ayu Wulandari",
        avatarColor: "#0891b2",
        joinedAt: hoursAgo(1),
        status: "online",
        answered: 0,
        total: 12,
        currentIndex: 0,
        score: 0,
        tabSwitchCount: 0,
      },
    ],
    createdAt: hoursAgo(26),
  },
  {
    id: "ses-kepribadian-selfpaced",
    code: "PSI910",
    packageId: "pkg-kepribadian",
    hostId: "usr-admin",
    title: bi("Tes Kepribadian – Self-paced", "Personality Test – Self-paced"),
    mode: "self-paced",
    status: "ended",
    requireLogin: true,
    maxParticipants: null,
    shuffleQuestions: true,
    shuffleOptions: false,
    showResultsImmediately: true,
    leaderboard: false,
    extraTimeSeconds: 0,
    deadline: daysAgo(3),
    startedAt: daysAgo(5),
    endedAt: daysAgo(3),
    participants: [
      {
        id: "sp-5",
        sessionId: "ses-kepribadian-selfpaced",
        userId: "usr-participant-2",
        name: "Dimas Saputra",
        avatarColor: "#16a34a",
        joinedAt: daysAgo(5),
        status: "finished",
        answered: 12,
        total: 12,
        currentIndex: 12,
        score: 45,
        finishedAt: daysAgo(4),
        tabSwitchCount: 0,
      },
      {
        id: "sp-6",
        sessionId: "ses-kepribadian-selfpaced",
        userId: "usr-participant-3",
        name: "Nadia Rahmawati",
        avatarColor: "#db2777",
        joinedAt: daysAgo(5),
        status: "finished",
        answered: 12,
        total: 12,
        currentIndex: 12,
        score: 51,
        finishedAt: daysAgo(4),
        tabSwitchCount: 2,
      },
    ],
    createdAt: daysAgo(6),
  },
];
