import type { Category, ConversionTable, Subtest, TestType } from "@/types";
import { bi } from "./helpers";

export const SEED_CATEGORIES: Category[] = [
  {
    id: "cat-skd",
    slug: "skd-cpns",
    name: bi("SKD CPNS", "CPNS Basic Test"),
    icon: "Landmark",
    color: "from-indigo-500 to-violet-500",
    order: 1,
  },
  {
    id: "cat-toefl",
    slug: "toefl",
    name: bi("TOEFL & Bahasa Inggris", "TOEFL & English"),
    icon: "Languages",
    color: "from-sky-500 to-cyan-500",
    order: 2,
  },
  {
    id: "cat-psikotes",
    slug: "psikotes",
    name: bi("Psikotes", "Psychometric Test"),
    icon: "Brain",
    color: "from-violet-500 to-fuchsia-500",
    order: 3,
  },
  {
    id: "cat-umum",
    slug: "tes-umum",
    name: bi("Tes Umum", "General Test"),
    icon: "ClipboardList",
    color: "from-emerald-500 to-teal-500",
    order: 4,
  },
  {
    id: "cat-utbk",
    slug: "utbk",
    name: bi("UTBK", "UTBK"),
    icon: "GraduationCap",
    color: "from-amber-500 to-orange-500",
    order: 5,
  },
  {
    id: "cat-kedinasan",
    slug: "kedinasan",
    name: bi("Masuk Kedinasan", "Civil Service Academy"),
    icon: "Building2",
    color: "from-rose-500 to-pink-500",
    order: 6,
  },
];

export const SEED_TEST_TYPES: TestType[] = [
  {
    id: "tt-skd",
    slug: "skd-cpns",
    name: bi("SKD CPNS", "CPNS Basic Competency Test"),
    description: bi(
      "Seleksi Kompetensi Dasar terdiri dari TWK, TIU, dan TKP dengan total waktu 100 menit.",
      "The Basic Competency Test consists of TWK, TIU and TKP with a total of 100 minutes.",
    ),
    icon: "Landmark",
    color: "indigo",
    order: 1,
    defaultDurationMinutes: 100,
    useConversionTable: false,
    resultKind: "score",
    createdAt: "2025-01-05T00:00:00.000Z",
    updatedAt: "2025-01-05T00:00:00.000Z",
  },
  {
    id: "tt-toefl",
    slug: "toefl-itp",
    name: bi("TOEFL ITP", "TOEFL ITP"),
    description: bi(
      "Listening, Structure & Written Expression, dan Reading dengan tabel konversi skor 310–677.",
      "Listening, Structure & Written Expression and Reading with a 310–677 score conversion table.",
    ),
    icon: "Languages",
    color: "sky",
    order: 2,
    defaultDurationMinutes: 115,
    useConversionTable: true,
    resultKind: "score",
    createdAt: "2025-01-05T00:00:00.000Z",
    updatedAt: "2025-01-05T00:00:00.000Z",
  },
  {
    id: "tt-psikotes",
    slug: "psikotes",
    name: bi("Psikotes", "Psychometric Test"),
    description: bi(
      "Tes kecerdasan, kecermatan, dan kepribadian. Tes kepribadian menghasilkan profil dimensi.",
      "Intelligence, accuracy and personality tests. Personality produces a dimension profile.",
    ),
    icon: "Brain",
    color: "violet",
    order: 3,
    defaultDurationMinutes: 90,
    useConversionTable: false,
    resultKind: "score",
    createdAt: "2025-01-05T00:00:00.000Z",
    updatedAt: "2025-01-05T00:00:00.000Z",
  },
  {
    id: "tt-umum",
    slug: "tes-umum",
    name: bi("Tes Umum", "General Test"),
    description: bi(
      "Tipe tes bebas: admin dapat membuat subtes dan aturan penilaian sendiri.",
      "A free-form test type: admins create their own subtests and scoring rules.",
    ),
    icon: "ClipboardList",
    color: "emerald",
    order: 4,
    defaultDurationMinutes: 75,
    useConversionTable: false,
    resultKind: "score",
    createdAt: "2025-01-05T00:00:00.000Z",
    updatedAt: "2025-01-05T00:00:00.000Z",
  },
  {
    id: "tt-utbk",
    slug: "utbk",
    name: bi("UTBK", "UTBK"),
    description: bi(
      "Ujian Tulis Berbasis Komputer: Penalaran Umum, Kuantitatif, dan Literasi.",
      "Computer-based written test: general reasoning, quantitative and literacy.",
    ),
    icon: "GraduationCap",
    color: "amber",
    order: 5,
    defaultDurationMinutes: 105,
    useConversionTable: false,
    resultKind: "score",
    createdAt: "2025-01-05T00:00:00.000Z",
    updatedAt: "2025-01-05T00:00:00.000Z",
  },
];

export const SEED_SUBTESTS: Subtest[] = [
  /* ------------------------------- SKD ------------------------------ */
  {
    id: "st-twk",
    testTypeId: "tt-skd",
    name: bi("Tes Wawasan Kebangsaan (TWK)", "National Insight Test (TWK)"),
    description: bi(
      "Mengukur penguasaan Pancasila, UUD 1945, NKRI, dan Bhinneka Tunggal Ika.",
      "Measures mastery of Pancasila, the 1945 Constitution, NKRI and Bhinneka Tunggal Ika.",
    ),
    instruction: bi(
      "Pilih satu jawaban yang paling tepat. Setiap jawaban benar bernilai 5 poin.",
      "Pick the single best answer. Each correct answer is worth 5 points.",
    ),
    order: 1,
    durationMinutes: null,
    questionCount: 30,
    scoring: { correct: 5, wrong: 0, empty: 0 },
    passingGrade: 65,
    allowedQuestionTypes: ["multiple-choice"],
    shuffleQuestions: true,
    shuffleOptions: true,
    allowBack: false,
    icon: "Flag",
    color: "indigo",
  },
  {
    id: "st-tiu",
    testTypeId: "tt-skd",
    name: bi("Tes Intelegensi Umum (TIU)", "General Intelligence Test (TIU)"),
    description: bi(
      "Kemampuan verbal, numerik, dan figural. Mengandung rumus matematika.",
      "Verbal, numeric and figural ability. Contains math formulas.",
    ),
    instruction: bi(
      "Beberapa soal memuat rumus. Kerjakan yang paling mudah terlebih dahulu.",
      "Some questions contain formulas. Start with the easiest ones.",
    ),
    order: 2,
    durationMinutes: null,
    questionCount: 35,
    scoring: { correct: 5, wrong: 0, empty: 0 },
    passingGrade: 80,
    allowedQuestionTypes: ["multiple-choice", "fill-blank"],
    shuffleQuestions: true,
    shuffleOptions: true,
    allowBack: false,
    icon: "Calculator",
    color: "violet",
  },
  {
    id: "st-tkp",
    testTypeId: "tt-skd",
    name: bi("Tes Karakteristik Pribadi (TKP)", "Personal Characteristics Test (TKP)"),
    description: bi(
      "Setiap pilihan memiliki bobot 1–5. Tidak ada jawaban salah.",
      "Each option carries a weight of 1–5. There is no wrong answer.",
    ),
    instruction: bi(
      "Pilih perilaku yang paling mencerminkan diri Anda. Bobot tertinggi 5.",
      "Choose the behaviour that best describes you. The highest weight is 5.",
    ),
    order: 3,
    durationMinutes: null,
    questionCount: 45,
    scoring: { correct: 1, wrong: 0, empty: 0 },
    passingGrade: 166,
    allowedQuestionTypes: ["weighted-choice"],
    shuffleQuestions: true,
    shuffleOptions: false,
    allowBack: false,
    icon: "Users",
    color: "emerald",
  },

  /* ------------------------------ TOEFL ----------------------------- */
  {
    id: "st-toefl-listening",
    testTypeId: "tt-toefl",
    name: bi("Listening Comprehension", "Listening Comprehension"),
    description: bi("Audio diputar satu kali. Tidak dapat diputar ulang.", "Audio plays once and cannot be replayed."),
    instruction: bi(
      "Dengarkan audio, lalu pilih jawaban terbaik. Audio hanya dapat diputar 1 kali.",
      "Listen to the audio, then pick the best answer. The audio can only be played once.",
    ),
    order: 1,
    durationMinutes: null,
    questionCount: 50,
    scoring: { correct: 1, wrong: 0, empty: 0 },
    passingGrade: null,
    allowedQuestionTypes: ["listening"],
    shuffleQuestions: false,
    shuffleOptions: false,
    allowBack: false,
    conversionTableId: "ct-listening",
    icon: "Headphones",
    color: "sky",
  },
  {
    id: "st-toefl-structure",
    testTypeId: "tt-toefl",
    name: bi("Structure & Written Expression", "Structure & Written Expression"),
    description: bi("Tata bahasa dan struktur kalimat bahasa Inggris.", "English grammar and sentence structure."),
    order: 2,
    durationMinutes: null,
    questionCount: 40,
    scoring: { correct: 1, wrong: 0, empty: 0 },
    passingGrade: null,
    allowedQuestionTypes: ["multiple-choice"],
    shuffleQuestions: true,
    shuffleOptions: true,
    allowBack: false,
    conversionTableId: "ct-structure",
    icon: "SpellCheck2",
    color: "cyan",
  },
  {
    id: "st-toefl-reading",
    testTypeId: "tt-toefl",
    name: bi("Reading Comprehension", "Reading Comprehension"),
    description: bi("Pemahaman bacaan akademik bahasa Inggris.", "Academic English reading comprehension."),
    order: 3,
    durationMinutes: null,
    questionCount: 50,
    scoring: { correct: 1, wrong: 0, empty: 0 },
    passingGrade: null,
    allowedQuestionTypes: ["multiple-choice", "group"],
    shuffleQuestions: true,
    shuffleOptions: true,
    allowBack: false,
    conversionTableId: "ct-reading",
    icon: "BookOpen",
    color: "blue",
  },

  /* ----------------------------- Psikotes --------------------------- */
  {
    id: "st-kecerdasan",
    testTypeId: "tt-psikotes",
    name: bi("Tes Kecerdasan", "Intelligence Test"),
    description: bi("Deret angka, logika, dan penalaran spasial.", "Number series, logic and spatial reasoning."),
    order: 1,
    durationMinutes: 20,
    questionCount: 20,
    scoring: { correct: 5, wrong: 0, empty: 0 },
    passingGrade: null,
    allowedQuestionTypes: ["multiple-choice"],
    shuffleQuestions: true,
    shuffleOptions: true,
    allowBack: true,
    icon: "Lightbulb",
    color: "violet",
  },
  {
    id: "st-kecermatan-karakter",
    testTypeId: "tt-psikotes",
    name: bi("Kecermatan: Karakter Hilang", "Accuracy: Missing Character"),
    description: bi(
      "Hafalkan 5 karakter kunci, lalu temukan karakter yang hilang dari 4 pilihan.",
      "Memorize 5 key characters, then find the missing one among 4 options.",
    ),
    instruction: bi(
      "Satu kolom berisi 8 soal dengan waktu 60 detik. Kolom berganti otomatis.",
      "One column holds 8 questions in 60 seconds. Columns advance automatically.",
    ),
    order: 2,
    durationMinutes: 8,
    questionCount: 64,
    scoring: { correct: 1, wrong: 0, empty: 0 },
    passingGrade: null,
    allowedQuestionTypes: ["kecermatan-karakter"],
    shuffleQuestions: false,
    shuffleOptions: false,
    allowBack: false,
    generator: {
      kind: "kecermatan-karakter",
      variant: "mixed",
      columns: 8,
      itemsPerColumn: 8,
      secondsPerColumn: 60,
      autoAdvance: true,
    },
    icon: "Eye",
    color: "fuchsia",
  },
  {
    id: "st-kecermatan-kraepelin",
    testTypeId: "tt-psikotes",
    name: bi("Kecermatan: Kraepelin / Pauli", "Accuracy: Kraepelin / Pauli"),
    description: bi(
      "Jumlahkan dua angka berdekatan, lalu ketik digit terakhirnya.",
      "Add two adjacent numbers, then type the last digit of the sum.",
    ),
    instruction: bi(
      "Gunakan keypad angka. Setiap kolom memiliki waktu 60 detik.",
      "Use the numeric keypad. Each column has 60 seconds.",
    ),
    order: 3,
    durationMinutes: 10,
    questionCount: 10,
    scoring: { correct: 1, wrong: 0, empty: 0 },
    passingGrade: null,
    allowedQuestionTypes: ["kecermatan-kraepelin"],
    shuffleQuestions: false,
    shuffleOptions: false,
    allowBack: false,
    generator: {
      kind: "kecermatan-kraepelin",
      columns: 10,
      rowsPerColumn: 30,
      secondsPerColumn: 60,
      autoAdvance: true,
      minDigit: 1,
      maxDigit: 9,
    },
    icon: "ListOrdered",
    color: "pink",
  },
  {
    id: "st-kecermatan-perbandingan",
    testTypeId: "tt-psikotes",
    name: bi("Kecermatan: Perbandingan Angka", "Accuracy: Number Comparison"),
    description: bi("Bandingkan dua angka atau ekspresi: kurang dari, lebih dari, atau sama dengan.", "Compare two numbers or expressions: less than, greater than, or equal."),
    order: 4,
    durationMinutes: 3,
    questionCount: 120,
    scoring: { correct: 1, wrong: 0, empty: 0 },
    passingGrade: null,
    allowedQuestionTypes: ["kecermatan-perbandingan"],
    shuffleQuestions: false,
    shuffleOptions: false,
    allowBack: false,
    generator: {
      kind: "kecermatan-perbandingan",
      columns: 6,
      itemsPerColumn: 20,
      secondsPerColumn: 30,
      autoAdvance: true,
      maxValue: 999,
      withExpression: true,
    },
    icon: "ArrowLeftRight",
    color: "rose",
  },
  {
    id: "st-kepribadian",
    testTypeId: "tt-psikotes",
    name: bi("Tes Kepribadian Big Five", "Big Five Personality Test"),
    description: bi(
      "Skala Likert 1–5 yang dipetakan ke lima dimensi kepribadian.",
      "A 1–5 Likert scale mapped onto five personality dimensions.",
    ),
    instruction: bi(
      "Pilih angka yang paling menggambarkan diri Anda. Tidak ada jawaban benar atau salah.",
      "Pick the number that describes you best. There is no right or wrong answer.",
    ),
    order: 5,
    durationMinutes: 15,
    questionCount: 30,
    scoring: { correct: 1, wrong: 0, empty: 0 },
    passingGrade: null,
    allowedQuestionTypes: ["likert"],
    shuffleQuestions: true,
    shuffleOptions: false,
    allowBack: true,
    resultKind: "profile",
    dimensions: [
      { key: "O", label: bi("Keterbukaan", "Openness"), color: "#8b5cf6" },
      { key: "C", label: bi("Ketelitian", "Conscientiousness"), color: "#22c55e" },
      { key: "E", label: bi("Ekstraversi", "Extraversion"), color: "#f59e0b" },
      { key: "A", label: bi("Keramahan", "Agreeableness"), color: "#06b6d4" },
      { key: "N", label: bi("Stabilitas Emosi", "Emotional Stability"), color: "#ef4444" },
    ],
    icon: "UserRound",
    color: "indigo",
  },

  /* ---------------------------- Tes Umum ---------------------------- */
  {
    id: "st-umum-pu",
    testTypeId: "tt-umum",
    name: bi("Pengetahuan Umum", "General Knowledge"),
    description: bi("Pengetahuan umum dan wawasan digital.", "General knowledge and digital literacy."),
    order: 1,
    durationMinutes: 20,
    questionCount: 20,
    scoring: { correct: 5, wrong: 0, empty: 0 },
    passingGrade: 60,
    allowedQuestionTypes: [
      "multiple-choice",
      "multiple-answer",
      "true-false",
      "matching",
      "ordering",
      "fill-blank",
      "image-choice",
    ],
    shuffleQuestions: true,
    shuffleOptions: true,
    allowBack: true,
    icon: "Globe",
    color: "emerald",
  },
  {
    id: "st-umum-logika",
    testTypeId: "tt-umum",
    name: bi("Logika & Numerik", "Logic & Numeric"),
    description: bi("Penalaran logis dan hitungan. Jawaban salah mengurangi poin.", "Logical and numeric reasoning. Wrong answers cost points."),
    instruction: bi(
      "Hati-hati: jawaban salah bernilai -1 poin, soal kosong 0 poin.",
      "Careful: a wrong answer is -1 point, a blank one is 0 points.",
    ),
    order: 2,
    durationMinutes: 25,
    questionCount: 15,
    scoring: { correct: 4, wrong: -1, empty: 0 },
    passingGrade: 30,
    allowedQuestionTypes: ["multiple-choice", "fill-blank"],
    shuffleQuestions: true,
    shuffleOptions: false,
    allowBack: true,
    icon: "Sigma",
    color: "teal",
  },
  {
    id: "st-umum-esai",
    testTypeId: "tt-umum",
    name: bi("Esai Singkat", "Short Essay"),
    description: bi("Dinilai manual oleh admin menggunakan rubrik.", "Graded manually by an admin using a rubric."),
    instruction: bi(
      "Tuliskan jawaban minimal 50 kata. Skor akan muncul setelah dinilai admin.",
      "Write at least 50 words. The score appears after an admin grades it.",
    ),
    order: 3,
    durationMinutes: 20,
    questionCount: 3,
    scoring: { correct: 10, wrong: 0, empty: 0 },
    passingGrade: null,
    allowedQuestionTypes: ["essay"],
    shuffleQuestions: false,
    shuffleOptions: false,
    allowBack: true,
    icon: "PenLine",
    color: "lime",
  },

  /* ------------------------------- UTBK ----------------------------- */
  {
    id: "st-utbk-pu",
    testTypeId: "tt-utbk",
    name: bi("Penalaran Umum", "General Reasoning"),
    order: 1,
    durationMinutes: 30,
    questionCount: 20,
    scoring: { correct: 1, wrong: 0, empty: 0 },
    passingGrade: null,
    allowedQuestionTypes: ["multiple-choice"],
    shuffleQuestions: true,
    shuffleOptions: true,
    allowBack: true,
    icon: "Brain",
    color: "amber",
  },
  {
    id: "st-utbk-kuantitatif",
    testTypeId: "tt-utbk",
    name: bi("Kuantitatif", "Quantitative"),
    order: 2,
    durationMinutes: 40,
    questionCount: 20,
    scoring: { correct: 1, wrong: 0, empty: 0 },
    passingGrade: null,
    allowedQuestionTypes: ["multiple-choice", "fill-blank"],
    shuffleQuestions: true,
    shuffleOptions: true,
    allowBack: true,
    icon: "Sigma",
    color: "orange",
  },
  {
    id: "st-utbk-literasi",
    testTypeId: "tt-utbk",
    name: bi("Literasi Bahasa", "Language Literacy"),
    order: 3,
    durationMinutes: 35,
    questionCount: 20,
    scoring: { correct: 1, wrong: 0, empty: 0 },
    passingGrade: null,
    allowedQuestionTypes: ["multiple-choice", "group"],
    shuffleQuestions: true,
    shuffleOptions: true,
    allowBack: true,
    icon: "BookOpen",
    color: "yellow",
  },
];

/* ---------------------- TOEFL conversion tables --------------------- */

function buildEntries(pairs: [number, number][]): { raw: number; scaled: number }[] {
  return pairs.map(([raw, scaled]) => ({ raw, scaled }));
}

export const SEED_CONVERSION_TABLES: ConversionTable[] = [
  {
    id: "ct-listening",
    testTypeId: "tt-toefl",
    name: bi("Konversi Listening (raw → 31–68)", "Listening conversion (raw → 31–68)"),
    min: 31,
    max: 68,
    entries: buildEntries([
      [0, 31],
      [1, 31],
      [2, 32],
      [3, 33],
      [4, 34],
      [5, 35],
      [6, 36],
      [7, 37],
      [8, 38],
      [9, 39],
      [10, 40],
      [12, 42],
      [14, 44],
      [16, 46],
      [18, 48],
      [20, 50],
      [23, 52],
      [26, 54],
      [29, 56],
      [32, 58],
      [35, 60],
      [38, 62],
      [41, 64],
      [44, 66],
      [47, 67],
      [50, 68],
    ]),
  },
  {
    id: "ct-structure",
    testTypeId: "tt-toefl",
    name: bi("Konversi Structure (raw → 31–68)", "Structure conversion (raw → 31–68)"),
    min: 31,
    max: 68,
    entries: buildEntries([
      [0, 31],
      [1, 32],
      [2, 33],
      [3, 34],
      [4, 35],
      [5, 36],
      [6, 37],
      [7, 38],
      [8, 39],
      [9, 40],
      [11, 42],
      [13, 44],
      [15, 46],
      [17, 48],
      [19, 50],
      [22, 52],
      [25, 54],
      [28, 56],
      [31, 58],
      [34, 60],
      [36, 62],
      [38, 64],
      [39, 66],
      [40, 68],
    ]),
  },
  {
    id: "ct-reading",
    testTypeId: "tt-toefl",
    name: bi("Konversi Reading (raw → 31–67)", "Reading conversion (raw → 31–67)"),
    min: 31,
    max: 67,
    entries: buildEntries([
      [0, 31],
      [1, 32],
      [2, 33],
      [3, 34],
      [4, 35],
      [5, 36],
      [6, 37],
      [7, 38],
      [8, 39],
      [9, 40],
      [11, 42],
      [13, 44],
      [15, 45],
      [17, 46],
      [19, 47],
      [22, 48],
      [25, 50],
      [28, 52],
      [31, 54],
      [34, 56],
      [37, 58],
      [40, 60],
      [43, 62],
      [46, 64],
      [48, 66],
      [50, 67],
    ]),
  },
];
