import type { User } from "@/types";
import { daysAgo, hoursAgo } from "./helpers";

export const SEED_USERS: User[] = [
  {
    id: "usr-admin",
    name: "Rina Kartika",
    email: "admin@tryoutku.id",
    password: "admin123",
    role: "admin",
    phone: "0812-9000-1122",
    institution: "TryoutKu",
    avatarColor: "#4f46e5",
    status: "active",
    createdAt: daysAgo(420),
    lastLoginAt: hoursAgo(3),
  },
  {
    id: "usr-host",
    name: "Bagus Pratama, S.Pd.",
    email: "pengajar@tryoutku.id",
    password: "pengajar123",
    role: "host",
    phone: "0813-4455-6677",
    institution: "Bimbel Perkasa",
    avatarColor: "#0ea5e9",
    status: "active",
    createdAt: daysAgo(300),
    lastLoginAt: hoursAgo(20),
  },
  {
    id: "usr-participant",
    name: "Andini Lestari",
    email: "peserta@tryoutku.id",
    password: "peserta123",
    role: "participant",
    phone: "0857-2211-3344",
    institution: "Universitas Gadjah Mada",
    avatarColor: "#f97316",
    status: "active",
    createdAt: daysAgo(96),
    lastLoginAt: hoursAgo(5),
  },
  {
    id: "usr-participant-2",
    name: "Dimas Saputra",
    email: "dimas@email.com",
    password: "peserta123",
    role: "participant",
    institution: "Universitas Indonesia",
    avatarColor: "#16a34a",
    status: "active",
    createdAt: daysAgo(74),
    lastLoginAt: daysAgo(2),
  },
  {
    id: "usr-participant-3",
    name: "Nadia Rahmawati",
    email: "nadia@email.com",
    password: "peserta123",
    role: "participant",
    institution: "Institut Teknologi Bandung",
    avatarColor: "#db2777",
    status: "active",
    createdAt: daysAgo(51),
    lastLoginAt: daysAgo(1),
  },
  {
    id: "usr-participant-4",
    name: "Fajar Nugroho",
    email: "fajar@email.com",
    password: "peserta123",
    role: "participant",
    institution: "Universitas Airlangga",
    avatarColor: "#7c3aed",
    status: "active",
    createdAt: daysAgo(38),
    lastLoginAt: daysAgo(4),
  },
  {
    id: "usr-participant-5",
    name: "Sekar Ayu Wulandari",
    email: "sekar@email.com",
    password: "peserta123",
    role: "participant",
    institution: "Universitas Diponegoro",
    avatarColor: "#0891b2",
    status: "active",
    createdAt: daysAgo(22),
    lastLoginAt: hoursAgo(30),
  },
  {
    id: "usr-participant-6",
    name: "Rizky Aditya",
    email: "rizky@email.com",
    password: "peserta123",
    role: "participant",
    status: "suspended",
    avatarColor: "#64748b",
    createdAt: daysAgo(15),
  },
];

export const DEMO_CREDENTIALS = {
  admin: { email: "admin@tryoutku.id", password: "admin123" },
  host: { email: "pengajar@tryoutku.id", password: "pengajar123" },
  participant: { email: "peserta@tryoutku.id", password: "peserta123" },
} as const;
