"use client";

import { useState } from "react";
import Image from "next/image";
import { CheckCircle2, Copy, Loader2, QrCode, Upload } from "lucide-react";
import { toast } from "sonner";

import { useI18n } from "@/lib/i18n";
import { formatCurrency } from "@/lib/format";
import { dataSource } from "@/lib/repositories";
import { useCurrentUser } from "@/lib/store/auth";
import { useDatabase } from "@/lib/store/db";
import { compressImage } from "@/lib/utils/image";
import type { PaymentMethod, TryoutPackage } from "@/types";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Separator } from "@/components/ui/separator";
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle } from "@/components/ui/sheet";

/**
 * Manual payment flow: pick a method, apply a voucher, upload the transfer
 * proof. The 3-digit unique code is generated by the caller (an event handler)
 * so rendering stays pure.
 */
export function CheckoutSheet({
  pkg,
  open,
  uniqueCode,
  onOpenChange,
  onSuccess,
}: {
  pkg?: TryoutPackage;
  open: boolean;
  uniqueCode: number;
  onOpenChange: (open: boolean) => void;
  onSuccess?: () => void;
}) {
  const { t, tx } = useI18n();

  if (!pkg) return null;

  return (
    <Sheet open={open} onOpenChange={onOpenChange}>
      <SheetContent side="bottom" className="max-h-[90vh] overflow-y-auto">
        <SheetHeader>
          <SheetTitle>{t("checkout.title")}</SheetTitle>
          <SheetDescription className="truncate">{tx(pkg.title)}</SheetDescription>
        </SheetHeader>
        {open && (
          <CheckoutForm
            // Remount on every open so the form starts clean.
            key={`${pkg.id}-${open}`}
            pkg={pkg}
            uniqueCode={uniqueCode}
            onOpenChange={onOpenChange}
            onSuccess={onSuccess}
          />
        )}
      </SheetContent>
    </Sheet>
  );
}

function CheckoutForm({
  pkg,
  uniqueCode,
  onOpenChange,
  onSuccess,
}: {
  pkg: TryoutPackage;
  uniqueCode: number;
  onOpenChange: (open: boolean) => void;
  onSuccess?: () => void;
}) {
  const { t, tx, locale } = useI18n();
  const db = useDatabase();
  const user = useCurrentUser();

  const methods = db.settings.paymentMethods.filter((method) => method.active);
  const [methodId, setMethodId] = useState<string>(methods[0]?.id ?? "");
  const [voucherCode, setVoucherCode] = useState("");
  const [discount, setDiscount] = useState(0);
  const [voucherMessage, setVoucherMessage] = useState<string | null>(null);
  const [proof, setProof] = useState<{ dataUrl: string; name: string } | null>(null);
  const [submitting, setSubmitting] = useState(false);

  const basePrice = pkg.discountPrice ?? pkg.price;
  const total = Math.max(0, basePrice - discount) + uniqueCode;
  const method = methods.find((item) => item.id === methodId);

  async function applyVoucher() {
    if (!voucherCode.trim()) return;
    setVoucherMessage(null);
    const result = await dataSource.vouchers.validate(voucherCode, {
      packageId: pkg.id,
      amount: basePrice,
    });
    if (result.ok) {
      setDiscount(result.discount);
      setVoucherMessage(`${result.voucher.code} · -${formatCurrency(result.discount, locale)}`);
      toast.success(t("common.success"));
    } else {
      setDiscount(0);
      setVoucherMessage(t(`voucher.errors.${result.reason}`));
    }
  }

  async function handleFileChange(event: React.ChangeEvent<HTMLInputElement>) {
    const file = event.target.files?.[0];
    if (!file) return;
    const dataUrl = await compressImage(file);
    setProof({ dataUrl, name: file.name });
  }

  async function handleSubmit() {
    if (!user || !methodId) return;
    setSubmitting(true);
    const invoice = await dataSource.payments.createInvoice({
      userId: user.id,
      packageId: pkg.id,
      amount: basePrice,
      discount,
      voucherCode: voucherCode.trim() || undefined,
      methodId,
    });
    if (proof) {
      await dataSource.payments.uploadProof(invoice.id, {
        proofUrl: proof.dataUrl,
        proofFileName: proof.name,
      });
    }
    await dataSource.activityLogs.add({
      userId: user.id,
      userName: user.name,
      action: "payment.uploaded",
      targetType: "payment",
      targetId: invoice.id,
      message: {
        id: `mengunggah bukti pembayaran ${invoice.invoiceCode}`,
        en: `uploaded payment proof ${invoice.invoiceCode}`,
      },
    });
    setSubmitting(false);
    toast.success(t("common.success"));
    onOpenChange(false);
    onSuccess?.();
  }

  return (
    <div className="space-y-4 px-4 pb-6">
      <div className="rounded-xl border border-border p-3">
        <div className="flex items-center justify-between text-sm">
          <span className="text-muted-foreground">{t("checkout.price")}</span>
          <span>{formatCurrency(basePrice, locale)}</span>
        </div>
        {discount > 0 && (
          <div className="mt-1 flex items-center justify-between text-sm text-success">
            <span>{t("checkout.discount")}</span>
            <span>-{formatCurrency(discount, locale)}</span>
          </div>
        )}
        <div className="mt-1 flex items-center justify-between text-sm">
          <span className="text-muted-foreground">{t("checkout.uniqueCode")}</span>
          <span className="font-mono">{uniqueCode}</span>
        </div>
        <Separator className="my-2" />
        <div className="flex items-center justify-between font-semibold">
          <span>{t("checkout.total")}</span>
          <span className="text-primary">{formatCurrency(total, locale)}</span>
        </div>
      </div>

      <div className="space-y-1.5">
        <Label htmlFor="voucher">{t("checkout.voucher")}</Label>
        <div className="flex gap-2">
          <Input
            id="voucher"
            value={voucherCode}
            onChange={(event) => setVoucherCode(event.target.value.toUpperCase())}
            placeholder="PERKASA10"
            className="font-mono"
          />
          <Button type="button" variant="outline" onClick={applyVoucher} disabled={!voucherCode.trim()}>
            {t("common.apply")}
          </Button>
        </div>
        {voucherMessage && (
          <p className={`text-xs ${discount > 0 ? "text-success" : "text-destructive"}`}>{voucherMessage}</p>
        )}
      </div>

      <div className="space-y-2">
        <Label>{t("checkout.method")}</Label>
        <div className="space-y-2">
          {methods.map((item) => (
            <MethodRow
              key={item.id}
              method={item}
              selected={methodId === item.id}
              onSelect={() => setMethodId(item.id)}
            />
          ))}
        </div>
      </div>

      {method && (
        <div className="space-y-2 rounded-xl border border-border bg-muted/40 p-3">
          <p className="text-sm font-semibold">{t("checkout.instructions")}</p>
          <div className="flex items-center justify-between gap-2 rounded-lg bg-background p-2">
            <span className="truncate font-mono text-sm">{method.accountNumber}</span>
            <Button
              type="button"
              size="xs"
              variant="ghost"
              onClick={async () => {
                await navigator.clipboard.writeText(method.accountNumber);
                toast.success(t("common.copied"));
              }}
            >
              <Copy className="size-3.5" />
              {t("common.copy")}
            </Button>
          </div>
          <p className="text-xs text-muted-foreground">
            {method.accountName}
            {method.instructions ? ` · ${tx(method.instructions)}` : ""}
          </p>
          {method.qrUrl && (
            <div className="flex justify-center">
              <Image
                src={method.qrUrl}
                alt={method.name}
                width={180}
                height={180}
                className="rounded-lg border border-border bg-white p-1"
              />
            </div>
          )}
        </div>
      )}

      <div className="space-y-1.5">
        <Label htmlFor="proof">{t("checkout.uploadProof")}</Label>
        <Input id="proof" type="file" accept="image/*" onChange={handleFileChange} className="h-auto py-2" />
        {proof ? (
          <div className="overflow-hidden rounded-lg border border-border">
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img src={proof.dataUrl} alt={proof.name} className="max-h-48 w-full object-contain" />
          </div>
        ) : (
          <p className="text-xs text-muted-foreground">{t("checkout.proofHint")}</p>
        )}
      </div>

      <Button className="w-full" size="lg" onClick={handleSubmit} disabled={submitting || !methodId}>
        {submitting ? <Loader2 className="size-4 animate-spin" /> : <Upload className="size-4" />}
        {t("checkout.submit")}
      </Button>

      <p className="text-center text-xs text-muted-foreground">
        {db.settings.autoApprovePayments ? t("checkout.autoApproveOn") : t("checkout.reviewNotice")}
      </p>
    </div>
  );
}

function MethodRow({
  method,
  selected,
  onSelect,
}: {
  method: PaymentMethod;
  selected: boolean;
  onSelect: () => void;
}) {
  return (
    <button
      type="button"
      onClick={onSelect}
      aria-pressed={selected}
      className={`flex w-full items-center gap-3 rounded-xl border p-3 text-left transition-colors ${
        selected ? "border-primary bg-primary/5" : "border-border hover:bg-accent"
      }`}
    >
      <span className="flex size-9 items-center justify-center rounded-lg bg-muted">
        {method.kind === "qris" ? (
          <QrCode className="size-4" />
        ) : (
          <span className="text-[0.625rem] font-bold uppercase">{method.kind.slice(0, 3)}</span>
        )}
      </span>
      <span className="min-w-0 flex-1">
        <span className="block text-sm font-semibold">{method.name}</span>
        <span className="block truncate text-xs text-muted-foreground">
          {method.accountNumber} · {method.accountName}
        </span>
      </span>
      {selected && <CheckCircle2 className="size-5 text-primary" />}
    </button>
  );
}
