import type { Question } from "@/types";
import { bi, m, options, p, q, rich } from "../helpers";

/* =========================== KECERDASAN =========================== */

const KECERDASAN: Question[] = [
  q({
    id: "q-psi-cer-01",
    type: "multiple-choice",
    testTypeId: "tt-psikotes",
    subtestId: "st-kecerdasan",
    difficulty: "easy",
    topics: ["Deret Angka"],
    tags: ["kecerdasan", "deret"],
    prompt: rich(p("2, 5, 11, 23, …")),
    options: options([
      { key: "a", id: "41" },
      { key: "b", id: "45" },
      { key: "c", id: "46" },
      { key: "d", id: "47" },
    ]),
    correctOptionId: "d",
    explanation: rich(p("Pola: " + m("n \\times 2 + 1") + ". " + m("23 \\times 2 + 1 = 47") + ".")),
  }),
  q({
    id: "q-psi-cer-02",
    type: "multiple-choice",
    testTypeId: "tt-psikotes",
    subtestId: "st-kecerdasan",
    difficulty: "medium",
    topics: ["Deret Huruf"],
    tags: ["kecerdasan", "deret"],
    prompt: rich(p("A, C, F, J, O, …")),
    options: options([
      { key: "a", id: "R" },
      { key: "b", id: "S" },
      { key: "c", id: "T" },
      { key: "d", id: "U" },
    ]),
    correctOptionId: "d",
    explanation: rich(p("Lompatan bertambah: +2, +3, +4, +5, maka berikutnya +6 dari O = U.")),
  }),
  q({
    id: "q-psi-cer-03",
    type: "multiple-choice",
    testTypeId: "tt-psikotes",
    subtestId: "st-kecerdasan",
    difficulty: "medium",
    topics: ["Logika"],
    tags: ["kecerdasan", "logika"],
    prompt: rich(p("Jika semua A adalah B, dan sebagian B adalah C, maka …")),
    options: options([
      { key: "a", id: "Semua A adalah C" },
      { key: "b", id: "Sebagian A pasti C" },
      { key: "c", id: "Tidak dapat dipastikan bahwa A adalah C" },
      { key: "d", id: "Tidak ada A yang C" },
    ]),
    correctOptionId: "c",
    explanation: rich(p("Hubungan A–C tidak dapat disimpulkan pasti dari premis tersebut.")),
  }),
  q({
    id: "q-psi-cer-04",
    type: "multiple-choice",
    testTypeId: "tt-psikotes",
    subtestId: "st-kecerdasan",
    difficulty: "hard",
    topics: ["Aritmetika"],
    tags: ["kecerdasan", "hitungan"],
    prompt: rich(p("Sebuah toko memberi diskon 20% lalu tambahan 10% untuk member. Total harga akhir dari barang Rp500.000 adalah …")),
    options: options([
      { key: "a", id: "Rp350.000" },
      { key: "b", id: "Rp360.000" },
      { key: "c", id: "Rp370.000" },
      { key: "d", id: "Rp400.000" },
    ]),
    correctOptionId: "b",
    explanation: rich(
      p("Diskon bertingkat dikalikan: " + m("500.000 \\times 0{,}8 \\times 0{,}9 = 360.000") + "."),
    ),
  }),
  q({
    id: "q-psi-cer-05",
    type: "multiple-choice",
    testTypeId: "tt-psikotes",
    subtestId: "st-kecerdasan",
    difficulty: "medium",
    topics: ["Penalaran Spasial"],
    tags: ["kecerdasan", "spasial"],
    prompt: rich(
      p("Sebuah kubus memiliki 6 sisi. Jika tiga sisi yang saling berhadapan berwarna merah, biru, dan hijau, jumlah rusuk kubus tersebut adalah …"),
    ),
    options: options([
      { key: "a", id: "8" },
      { key: "b", id: "10" },
      { key: "c", id: "12" },
      { key: "d", id: "14" },
    ]),
    correctOptionId: "c",
    explanation: rich(p("Kubus selalu memiliki 12 rusuk, 6 sisi, dan 8 titik sudut.")),
  }),
  q({
    id: "q-psi-cer-06",
    type: "multiple-choice",
    testTypeId: "tt-psikotes",
    subtestId: "st-kecerdasan",
    difficulty: "easy",
    topics: ["Analogi"],
    tags: ["kecerdasan", "analogi"],
    prompt: rich(p("BUKU : PERPUSTAKAAN = OBAT : …")),
    options: options([
      { key: "a", id: "Dokter" },
      { key: "b", id: "Rumah sakit" },
      { key: "c", id: "Apotek" },
      { key: "d", id: "Resep" },
    ]),
    correctOptionId: "c",
    explanation: rich(p("Hubungan benda dengan tempat penyimpanannya: buku di perpustakaan, obat di apotek.")),
  }),
  q({
    id: "q-psi-cer-07",
    type: "multiple-choice",
    testTypeId: "tt-psikotes",
    subtestId: "st-kecerdasan",
    difficulty: "hard",
    topics: ["Logika Kuantitatif"],
    tags: ["kecerdasan", "logika"],
    prompt: rich(p("Rata-rata 5 bilangan adalah 18. Jika satu bilangan dihapus, rata-rata menjadi 16. Bilangan yang dihapus adalah …")),
    options: options([
      { key: "a", id: "22" },
      { key: "b", id: "24" },
      { key: "c", id: "26" },
      { key: "d", id: "28" },
    ]),
    correctOptionId: "c",
    explanation: rich(p("Total awal " + m("5 \\times 18 = 90") + ", total baru " + m("4 \\times 16 = 64") + ", selisih " + m("90 - 64 = 26") + ".")),
  }),
  q({
    id: "q-psi-cer-08",
    type: "multiple-choice",
    testTypeId: "tt-psikotes",
    subtestId: "st-kecerdasan",
    difficulty: "medium",
    topics: ["Silogisme"],
    tags: ["kecerdasan", "logika"],
    prompt: rich(p("Jika hujan turun, jalanan basah. Jalanan tidak basah. Maka …")),
    options: options([
      { key: "a", id: "Hujan turun" },
      { key: "b", id: "Hujan tidak turun" },
      { key: "c", id: "Jalanan licin" },
      { key: "d", id: "Tidak ada kesimpulan" },
    ]),
    correctOptionId: "b",
    explanation: rich(p("Modus tollens: menafikan akibat berarti menafikan sebab.")),
  }),
  q({
    id: "q-psi-cer-09",
    type: "multiple-choice",
    testTypeId: "tt-psikotes",
    subtestId: "st-kecerdasan",
    difficulty: "medium",
    topics: ["Deret Campuran"],
    tags: ["kecerdasan", "deret"],
    prompt: rich(p("1, 1, 2, 3, 5, 8, …")),
    options: options([
      { key: "a", id: "11" },
      { key: "b", id: "12" },
      { key: "c", id: "13" },
      { key: "d", id: "15" },
    ]),
    correctOptionId: "c",
    explanation: rich(p("Deret Fibonacci: setiap suku adalah jumlah dua suku sebelumnya (" + m("5 + 8 = 13") + ").")),
  }),
  q({
    id: "q-psi-cer-10",
    type: "multiple-choice",
    testTypeId: "tt-psikotes",
    subtestId: "st-kecerdasan",
    difficulty: "hard",
    topics: ["Penalaran Verbal"],
    tags: ["kecerdasan", "verbal"],
    prompt: rich(p("Lawan kata dari <strong>transparan</strong> adalah …")),
    options: options([
      { key: "a", id: "Jernih" },
      { key: "b", id: "Samar" },
      { key: "c", id: "Terbuka" },
      { key: "d", id: "Terang" },
    ]),
    correctOptionId: "b",
    explanation: rich(p("Transparan berarti jelas/tembus pandang, lawannya samar atau kabur.")),
  }),
];

/* ========================== KEPRIBADIAN ========================== */

const likertLabels = {
  min: bi("Sangat tidak setuju", "Strongly disagree"),
  max: bi("Sangat setuju", "Strongly agree"),
};

const KEPRIBADIAN: Question[] = [
  q({
    id: "q-psi-kep-01",
    type: "likert",
    testTypeId: "tt-psikotes",
    subtestId: "st-kepribadian",
    difficulty: "easy",
    topics: ["Big Five"],
    tags: ["kepribadian", "likert"],
    prompt: rich(p("Seberapa setuju Anda dengan pernyataan berikut?")),
    statement: rich(p("Saya senang mencoba ide dan pengalaman baru.")),
    min: 1,
    max: 5,
    minLabel: likertLabels.min,
    maxLabel: likertLabels.max,
    dimension: "O",
    reversed: false,
    explanation: rich(p("Item ini mengukur dimensi <strong>Keterbukaan (Openness)</strong>.")),
  }),
  q({
    id: "q-psi-kep-02",
    type: "likert",
    testTypeId: "tt-psikotes",
    subtestId: "st-kepribadian",
    difficulty: "easy",
    topics: ["Big Five"],
    tags: ["kepribadian", "likert"],
    prompt: rich(p("Seberapa setuju Anda dengan pernyataan berikut?")),
    statement: rich(p("Saya lebih suka rutinitas yang sudah pasti daripada perubahan mendadak.")),
    min: 1,
    max: 5,
    minLabel: likertLabels.min,
    maxLabel: likertLabels.max,
    dimension: "O",
    reversed: true,
    explanation: rich(p("Item <em>reverse-scored</em> untuk dimensi Keterbukaan.")),
  }),
  q({
    id: "q-psi-kep-03",
    type: "likert",
    testTypeId: "tt-psikotes",
    subtestId: "st-kepribadian",
    difficulty: "easy",
    topics: ["Big Five"],
    tags: ["kepribadian", "likert"],
    prompt: rich(p("Seberapa setuju Anda dengan pernyataan berikut?")),
    statement: rich(p("Saya selalu memeriksa kembali pekerjaan saya sebelum dikumpulkan.")),
    min: 1,
    max: 5,
    minLabel: likertLabels.min,
    maxLabel: likertLabels.max,
    dimension: "C",
    reversed: false,
    explanation: rich(p("Item ini mengukur dimensi <strong>Ketelitian (Conscientiousness)</strong>.")),
  }),
  q({
    id: "q-psi-kep-04",
    type: "likert",
    testTypeId: "tt-psikotes",
    subtestId: "st-kepribadian",
    difficulty: "easy",
    topics: ["Big Five"],
    tags: ["kepribadian", "likert"],
    prompt: rich(p("Seberapa setuju Anda dengan pernyataan berikut?")),
    statement: rich(p("Saya sering menunda pekerjaan hingga mendekati tenggat waktu.")),
    min: 1,
    max: 5,
    minLabel: likertLabels.min,
    maxLabel: likertLabels.max,
    dimension: "C",
    reversed: true,
    explanation: rich(p("Item <em>reverse-scored</em> untuk dimensi Ketelitian.")),
  }),
  q({
    id: "q-psi-kep-05",
    type: "likert",
    testTypeId: "tt-psikotes",
    subtestId: "st-kepribadian",
    difficulty: "easy",
    topics: ["Big Five"],
    tags: ["kepribadian", "likert"],
    prompt: rich(p("Seberapa setuju Anda dengan pernyataan berikut?")),
    statement: rich(p("Saya merasa bersemangat saat berada di tengah banyak orang.")),
    min: 1,
    max: 5,
    minLabel: likertLabels.min,
    maxLabel: likertLabels.max,
    dimension: "E",
    reversed: false,
    explanation: rich(p("Item ini mengukur dimensi <strong>Ekstraversi (Extraversion)</strong>.")),
  }),
  q({
    id: "q-psi-kep-06",
    type: "likert",
    testTypeId: "tt-psikotes",
    subtestId: "st-kepribadian",
    difficulty: "easy",
    topics: ["Big Five"],
    tags: ["kepribadian", "likert"],
    prompt: rich(p("Seberapa setuju Anda dengan pernyataan berikut?")),
    statement: rich(p("Saya lebih nyaman menghabiskan waktu sendiri daripada di keramaian.")),
    min: 1,
    max: 5,
    minLabel: likertLabels.min,
    maxLabel: likertLabels.max,
    dimension: "E",
    reversed: true,
    explanation: rich(p("Item <em>reverse-scored</em> untuk dimensi Ekstraversi.")),
  }),
  q({
    id: "q-psi-kep-07",
    type: "likert",
    testTypeId: "tt-psikotes",
    subtestId: "st-kepribadian",
    difficulty: "easy",
    topics: ["Big Five"],
    tags: ["kepribadian", "likert"],
    prompt: rich(p("Seberapa setuju Anda dengan pernyataan berikut?")),
    statement: rich(p("Saya mudah memahami perasaan orang lain tanpa harus dijelaskan.")),
    min: 1,
    max: 5,
    minLabel: likertLabels.min,
    maxLabel: likertLabels.max,
    dimension: "A",
    reversed: false,
    explanation: rich(p("Item ini mengukur dimensi <strong>Keramahan (Agreeableness)</strong>.")),
  }),
  q({
    id: "q-psi-kep-08",
    type: "likert",
    testTypeId: "tt-psikotes",
    subtestId: "st-kepribadian",
    difficulty: "easy",
    topics: ["Big Five"],
    tags: ["kepribadian", "likert"],
    prompt: rich(p("Seberapa setuju Anda dengan pernyataan berikut?")),
    statement: rich(p("Dalam perdebatan, saya lebih pentingkan menang daripada menjaga hubungan.")),
    min: 1,
    max: 5,
    minLabel: likertLabels.min,
    maxLabel: likertLabels.max,
    dimension: "A",
    reversed: true,
    explanation: rich(p("Item <em>reverse-scored</em> untuk dimensi Keramahan.")),
  }),
  q({
    id: "q-psi-kep-09",
    type: "likert",
    testTypeId: "tt-psikotes",
    subtestId: "st-kepribadian",
    difficulty: "easy",
    topics: ["Big Five"],
    tags: ["kepribadian", "likert"],
    prompt: rich(p("Seberapa setuju Anda dengan pernyataan berikut?")),
    statement: rich(p("Saya tetap tenang ketika menghadapi situasi yang menekan.")),
    min: 1,
    max: 5,
    minLabel: likertLabels.min,
    maxLabel: likertLabels.max,
    dimension: "N",
    reversed: false,
    explanation: rich(p("Item ini mengukur dimensi <strong>Stabilitas Emosi (Emotional Stability)</strong>.")),
  }),
  q({
    id: "q-psi-kep-10",
    type: "likert",
    testTypeId: "tt-psikotes",
    subtestId: "st-kepribadian",
    difficulty: "easy",
    topics: ["Big Five"],
    tags: ["kepribadian", "likert"],
    prompt: rich(p("Seberapa setuju Anda dengan pernyataan berikut?")),
    statement: rich(p("Kritik kecil dapat merusak suasana hati saya seharian.")),
    min: 1,
    max: 5,
    minLabel: likertLabels.min,
    maxLabel: likertLabels.max,
    dimension: "N",
    reversed: true,
    explanation: rich(p("Item <em>reverse-scored</em> untuk dimensi Stabilitas Emosi.")),
  }),
  q({
    id: "q-psi-kep-11",
    type: "likert",
    testTypeId: "tt-psikotes",
    subtestId: "st-kepribadian",
    difficulty: "easy",
    topics: ["Big Five"],
    tags: ["kepribadian", "likert"],
    prompt: rich(p("Seberapa setuju Anda dengan pernyataan berikut?")),
    statement: rich(p("Saya suka mempelajari topik baru meski tidak ada hubungannya dengan pekerjaan saya.")),
    min: 1,
    max: 5,
    minLabel: likertLabels.min,
    maxLabel: likertLabels.max,
    dimension: "O",
    reversed: false,
    explanation: rich(p("Item tambahan untuk dimensi Keterbukaan.")),
  }),
  q({
    id: "q-psi-kep-12",
    type: "likert",
    testTypeId: "tt-psikotes",
    subtestId: "st-kepribadian",
    difficulty: "easy",
    topics: ["Big Five"],
    tags: ["kepribadian", "likert"],
    prompt: rich(p("Seberapa setuju Anda dengan pernyataan berikut?")),
    statement: rich(p("Saya membuat daftar tugas harian dan menaatinya.")),
    min: 1,
    max: 5,
    minLabel: likertLabels.min,
    maxLabel: likertLabels.max,
    dimension: "C",
    reversed: false,
    explanation: rich(p("Item tambahan untuk dimensi Ketelitian.")),
  }),
];

export const PSIKOTES_QUESTIONS: Question[] = [...KECERDASAN, ...KEPRIBADIAN];
export const KECERDASAN_QUESTION_IDS = KECERDASAN.map((item) => item.id);
export const KEPRIBADIAN_QUESTION_IDS = KEPRIBADIAN.map((item) => item.id);
