import type { Question } from "@/types";
import { m, mb, options, p, q, rich, ul } from "../helpers";

/* ============================== TWK ============================== */

const TWK: Question[] = [
  q({
    id: "q-twk-01",
    type: "multiple-choice",
    testTypeId: "tt-skd",
    subtestId: "st-twk",
    difficulty: "easy",
    topics: ["Pancasila"],
    tags: ["pancasila", "sila-pertama"],
    prompt: rich(
      p("Sila pertama Pancasila berbunyi …") +
        ul(["Kemanusiaan yang adil dan beradab", "Persatuan Indonesia", "Ketuhanan Yang Maha Esa", "Kerakyatan yang dipimpin oleh hikmat kebijaksanaan"]),
    ),
    options: options([
      { key: "a", id: "Kemanusiaan yang adil dan beradab", en: "Just and civilized humanity" },
      { key: "b", id: "Persatuan Indonesia", en: "The unity of Indonesia" },
      { key: "c", id: "Ketuhanan Yang Maha Esa", en: "Belief in the One Almighty God" },
      { key: "d", id: "Kerakyatan yang dipimpin oleh hikmat kebijaksanaan", en: "Democracy guided by wisdom" },
    ]),
    correctOptionId: "c",
    explanation: rich(
      p("Sila pertama Pancasila adalah <strong>Ketuhanan Yang Maha Esa</strong>, dilambangkan dengan bintang.") +
        p("Urutan lengkap: (1) Ketuhanan, (2) Kemanusiaan, (3) Persatuan, (4) Kerakyatan, (5) Keadilan sosial."),
    ),
  }),
  q({
    id: "q-twk-02",
    type: "multiple-choice",
    testTypeId: "tt-skd",
    subtestId: "st-twk",
    difficulty: "medium",
    topics: ["UUD 1945"],
    tags: ["uud1945", "amandemen"],
    prompt: rich(
      p("Perubahan (amandemen) UUD 1945 dilakukan dalam empat tahap pada periode …"),
    ),
    options: options([
      { key: "a", id: "1997–2000" },
      { key: "b", id: "1998–2001" },
      { key: "c", id: "1999–2002" },
      { key: "d", id: "2000–2003" },
    ]),
    correctOptionId: "c",
    explanation: rich(
      p("Amandemen UUD 1945 dilakukan oleh MPR pada 1999, 2000, 2001, dan 2002 (empat tahap)."),
    ),
  }),
  q({
    id: "q-twk-03",
    type: "multiple-choice",
    testTypeId: "tt-skd",
    subtestId: "st-twk",
    difficulty: "medium",
    topics: ["NKRI"],
    tags: ["negara", "bentuk-negara"],
    prompt: rich(
      p("Berdasarkan UUD 1945 Pasal 1 ayat (1), bentuk negara Indonesia adalah …"),
    ),
    options: options([
      { key: "a", id: "Federasi" },
      { key: "b", id: "Kesatuan" },
      { key: "c", id: "Monarki konstitusional" },
      { key: "d", id: "Republik federal" },
    ]),
    correctOptionId: "b",
    explanation: rich(
      p("Pasal 1 ayat (1) UUD 1945: “Negara Indonesia ialah Negara Kesatuan yang berbentuk Republik.”"),
    ),
  }),
  q({
    id: "q-twk-04",
    type: "multiple-choice",
    testTypeId: "tt-skd",
    subtestId: "st-twk",
    difficulty: "easy",
    topics: ["Bhinneka Tunggal Ika"],
    tags: ["semboyan", "keberagaman"],
    prompt: rich(
      p("Semboyan negara Indonesia “Bhinneka Tunggal Ika” memiliki makna …"),
    ),
    options: options([
      { key: "a", id: "Bersatu kita teguh, bercerai kita runtuh" },
      { key: "b", id: "Berbeda-beda tetapi tetap satu jua" },
      { key: "c", id: "Satu nusa, satu bangsa, satu bahasa" },
      { key: "d", id: "Keberagaman adalah kekayaan bangsa" },
    ]),
    correctOptionId: "b",
    explanation: rich(
      p("Secara harfiah <em>Bhinneka Tunggal Ika</em> berarti “beraneka ragam namun tetap satu”."),
    ),
  }),
  q({
    id: "q-twk-05",
    type: "multiple-choice",
    testTypeId: "tt-skd",
    subtestId: "st-twk",
    difficulty: "hard",
    topics: ["Wawasan Nusantara"],
    tags: ["geopolitik"],
    prompt: rich(
      p("Konsep Wawasan Nusantara memandang wilayah Indonesia sebagai satu kesatuan …"),
    ),
    options: options([
      { key: "a", id: "Politik, ekonomi, sosial budaya, dan pertahanan keamanan" },
      { key: "b", id: "Politik dan ekonomi saja" },
      { key: "c", id: "Wilayah daratan dan lautan secara terpisah" },
      { key: "d", id: "Kepulauan yang dikelola masing-masing daerah" },
    ]),
    correctOptionId: "a",
    explanation: rich(
      p("Wawasan Nusantara adalah cara pandang bangsa Indonesia terhadap diri dan lingkungannya sebagai satu kesatuan utuh dalam aspek politik, ekonomi, sosial budaya, dan pertahanan keamanan (Asta Gatra)."),
    ),
  }),
  q({
    id: "q-twk-06",
    type: "multiple-choice",
    testTypeId: "tt-skd",
    subtestId: "st-twk",
    difficulty: "medium",
    topics: ["Sistem Pemerintahan"],
    tags: ["lembaga-negara", "mpr"],
    prompt: rich(
      p("Lembaga negara yang memiliki wewenang mengubah dan menetapkan UUD 1945 adalah …"),
    ),
    options: options([
      { key: "a", id: "Presiden" },
      { key: "b", id: "Dewan Perwakilan Rakyat" },
      { key: "c", id: "Majelis Permusyawaratan Rakyat" },
      { key: "d", id: "Mahkamah Konstitusi" },
    ]),
    correctOptionId: "c",
    explanation: rich(
      p("Pasal 3 ayat (1) UUD 1945: MPR berwenang mengubah dan menetapkan Undang-Undang Dasar."),
    ),
  }),
  q({
    id: "q-twk-07",
    type: "multiple-choice",
    testTypeId: "tt-skd",
    subtestId: "st-twk",
    difficulty: "medium",
    topics: ["Hak dan Kewajiban Warga Negara"],
    tags: ["ham", "pasal-28"],
    prompt: rich(
      p("Jaminan kebebasan berserikat, berkumpul, dan mengeluarkan pendapat diatur dalam UUD 1945 Pasal …"),
    ),
    options: options([
      { key: "a", id: "28" },
      { key: "b", id: "28E ayat (3)" },
      { key: "c", id: "29" },
      { key: "d", id: "31" },
    ]),
    correctOptionId: "b",
    explanation: rich(
      p("Pasal 28E ayat (3): “Setiap orang berhak atas kebebasan berserikat, berkumpul, dan mengeluarkan pendapat.”"),
    ),
  }),
  q({
    id: "q-twk-08",
    type: "multiple-choice",
    testTypeId: "tt-skd",
    subtestId: "st-twk",
    difficulty: "hard",
    topics: ["Sejarah Nasional"],
    tags: ["sumpah-pemuda", "budi-utomo"],
    prompt: rich(p("Organisasi pergerakan nasional yang lahir pada 20 Mei 1908 adalah …")),
    options: options([
      { key: "a", id: "Sarekat Islam" },
      { key: "b", id: "Indische Partij" },
      { key: "c", id: "Budi Utomo" },
      { key: "d", id: "Perhimpunan Indonesia" },
    ]),
    correctOptionId: "c",
    explanation: rich(p("Budi Utomo didirikan 20 Mei 1908, kini diperingati sebagai Hari Kebangkitan Nasional.")),
  }),
  q({
    id: "q-twk-09",
    type: "multiple-choice",
    testTypeId: "tt-skd",
    subtestId: "st-twk",
    difficulty: "easy",
    topics: ["Pilar Negara"],
    tags: ["empat-pilar"],
    prompt: rich(p("Yang <strong>bukan</strong> termasuk pilar kebangsaan Indonesia adalah …")),
    options: options([
      { key: "a", id: "Pancasila" },
      { key: "b", id: "UUD 1945" },
      { key: "c", id: "Bhinneka Tunggal Ika" },
      { key: "d", id: "Undang-Undang Dasar 1949" },
    ]),
    correctOptionId: "d",
    explanation: rich(
      p("Empat pilar kebangsaan: Pancasila, UUD 1945, Bhinneka Tunggal Ika, dan NKRI."),
    ),
  }),
  q({
    id: "q-twk-10",
    type: "multiple-choice",
    testTypeId: "tt-skd",
    subtestId: "st-twk",
    difficulty: "medium",
    topics: ["Ketahanan Nasional"],
    tags: ["geostrategi"],
    prompt: rich(
      p("Dalam menyelesaikan konflik antarwarga, sikap yang paling mencerminkan nilai Pancasila adalah …"),
    ),
    options: options([
      { key: "a", id: "Menang sendiri agar tidak dianggap lemah" },
      { key: "b", id: "Menghindar dan membiarkan masalah berlalu" },
      { key: "c", id: "Mengutamakan musyawarah untuk mufakat" },
      { key: "d", id: "Menyerahkan sepenuhnya kepada aparat" },
    ]),
    correctOptionId: "c",
    explanation: rich(
      p("Musyawarah untuk mufakat adalah perwujudan sila ke-4 Pancasila dalam penyelesaian masalah bersama."),
    ),
  }),
];

/* ============================== TIU ============================== */

const TIU: Question[] = [
  q({
    id: "q-tiu-01",
    type: "multiple-choice",
    testTypeId: "tt-skd",
    subtestId: "st-tiu",
    difficulty: "easy",
    topics: ["Deret Angka"],
    tags: ["numerik", "deret"],
    prompt: rich(p("Lanjutkan deret berikut: 3, 6, 12, 24, …")),
    options: options([
      { key: "a", id: "36" },
      { key: "b", id: "42" },
      { key: "c", id: "48" },
      { key: "d", id: "54" },
    ]),
    correctOptionId: "c",
    explanation: rich(p("Pola perkalian 2: " + m("3 \\times 2 = 6") + ", " + m("6 \\times 2 = 12") + ", " + m("12 \\times 2 = 24") + ", maka " + m("24 \\times 2 = 48") + ".")),
  }),
  q({
    id: "q-tiu-02",
    type: "multiple-choice",
    testTypeId: "tt-skd",
    subtestId: "st-tiu",
    difficulty: "medium",
    topics: ["Perbandingan"],
    tags: ["numerik", "perbandingan"],
    prompt: rich(
      p("Sebuah proyek selesai dalam 12 hari oleh 8 pekerja. Jika dikerjakan oleh 6 pekerja dengan kecepatan sama, waktu yang dibutuhkan adalah …"),
    ),
    options: options([
      { key: "a", id: "14 hari" },
      { key: "b", id: "16 hari" },
      { key: "c", id: "18 hari" },
      { key: "d", id: "20 hari" },
    ]),
    correctOptionId: "b",
    explanation: rich(
      p("Total pekerjaan = " + m("8 \\times 12 = 96") + " orang-hari. Waktu untuk 6 pekerja = " + m("\\frac{96}{6} = 16") + " hari."),
    ),
  }),
  q({
    id: "q-tiu-03",
    type: "multiple-choice",
    testTypeId: "tt-skd",
    subtestId: "st-tiu",
    difficulty: "medium",
    topics: ["Aljabar"],
    tags: ["numerik", "persamaan", "rumus"],
    prompt: rich(
      p("Jika " + m("f(x) = 2x^{2} - 5x + 3") + ", nilai " + m("f(3)") + " adalah …"),
    ),
    options: options([
      { key: "a", id: "4" },
      { key: "b", id: "6" },
      { key: "c", id: "8" },
      { key: "d", id: "10" },
    ]),
    correctOptionId: "b",
    explanation: rich(
      p("Substitusi " + m("x = 3") + ":") +
        mb("f(3) = 2(3)^{2} - 5(3) + 3 = 2 \\cdot 9 - 15 + 3 = 18 - 15 + 3 = 6"),
    ),
  }),
  q({
    id: "q-tiu-04",
    type: "multiple-choice",
    testTypeId: "tt-skd",
    subtestId: "st-tiu",
    difficulty: "hard",
    topics: ["Persamaan Kuadrat"],
    tags: ["numerik", "akar", "rumus"],
    prompt: rich(
      p("Akar-akar persamaan kuadrat " + m("x^{2} - 7x + 12 = 0") + " adalah …"),
    ),
    options: options([
      { key: "a", id: "2 dan 6" },
      { key: "b", id: "3 dan 4" },
      { key: "c", id: "-3 dan -4" },
      { key: "d", id: "3 dan -4" },
    ]),
    correctOptionId: "b",
    explanation: rich(
      p("Faktorisasi:") + mb("x^{2} - 7x + 12 = (x - 3)(x - 4) = 0") + p("maka " + m("x = 3") + " atau " + m("x = 4") + "."),
    ),
  }),
  q({
    id: "q-tiu-05",
    type: "multiple-choice",
    testTypeId: "tt-skd",
    subtestId: "st-tiu",
    difficulty: "medium",
    topics: ["Geometri"],
    tags: ["geometri", "rumus", "lingkaran"],
    prompt: rich(
      p("Luas lingkaran dengan jari-jari " + m("r = 7") + " cm dan " + m("\\pi = \\frac{22}{7}") + " adalah …"),
    ),
    options: options([
      { key: "a", id: "77 cm²" },
      { key: "b", id: "154 cm²" },
      { key: "c", id: "308 cm²" },
      { key: "d", id: "44 cm²" },
    ]),
    correctOptionId: "b",
    explanation: rich(p("Luas:") + mb("L = \\pi r^{2} = \\frac{22}{7} \\times 7^{2} = \\frac{22}{7} \\times 49 = 154 \\text{ cm}^{2}")),
  }),
  q({
    id: "q-tiu-06",
    type: "multiple-choice",
    testTypeId: "tt-skd",
    subtestId: "st-tiu",
    difficulty: "medium",
    topics: ["Kecepatan"],
    tags: ["numerik", "fisika-dasar"],
    prompt: rich(
      p("Sebuah mobil menempuh 180 km dengan kecepatan rata-rata 60 km/jam. Waktu tempuhnya adalah …"),
    ),
    options: options([
      { key: "a", id: "2 jam" },
      { key: "b", id: "2,5 jam" },
      { key: "c", id: "3 jam" },
      { key: "d", id: "3,5 jam" },
    ]),
    correctOptionId: "c",
    explanation: rich(p("Gunakan " + m("t = \\frac{s}{v}") + ": " + m("t = \\frac{180}{60} = 3") + " jam.")),
  }),
  q({
    id: "q-tiu-07",
    type: "multiple-choice",
    testTypeId: "tt-skd",
    subtestId: "st-tiu",
    difficulty: "hard",
    topics: ["Peluang"],
    tags: ["peluang", "rumus"],
    prompt: rich(
      p("Dua dadu dilempar bersamaan. Peluang muncul jumlah mata dadu 7 adalah …"),
    ),
    options: options([
      { key: "a", id: m("\\frac{1}{6}") },
      { key: "b", id: m("\\frac{1}{9}") },
      { key: "c", id: m("\\frac{1}{12}") },
      { key: "d", id: m("\\frac{5}{36}") },
    ]),
    correctOptionId: "a",
    explanation: rich(
      p("Ada 6 pasangan berjumlah 7 dari 36 kemungkinan:") +
        mb("P = \\frac{6}{36} = \\frac{1}{6}"),
    ),
  }),
  q({
    id: "q-tiu-08",
    type: "multiple-choice",
    testTypeId: "tt-skd",
    subtestId: "st-tiu",
    difficulty: "easy",
    topics: ["Analogi Verbal"],
    tags: ["verbal", "analogi"],
    prompt: rich(p("DOKTER : PASIEN = PENGACARA : …")),
    options: options([
      { key: "a", id: "Pengadilan" },
      { key: "b", id: "Klien" },
      { key: "c", id: "Hakim" },
      { key: "d", id: "Jaksa" },
    ]),
    correctOptionId: "b",
    explanation: rich(p("Hubungan profesi dengan orang yang dilayani: dokter melayani pasien, pengacara melayani klien.")),
  }),
  q({
    id: "q-tiu-09",
    type: "multiple-choice",
    testTypeId: "tt-skd",
    subtestId: "st-tiu",
    difficulty: "hard",
    topics: ["Logika Kuantitatif"],
    tags: ["logika", "silogisme"],
    prompt: rich(
      p("Semua pegawai yang lulus ujian mendapat kenaikan gaji. Sebagian pegawai yang mendapat kenaikan gaji mengikuti pelatihan. Maka …"),
    ),
    options: options([
      { key: "a", id: "Semua peserta pelatihan lulus ujian" },
      { key: "b", id: "Sebagian pegawai yang lulus ujian mungkin mengikuti pelatihan" },
      { key: "c", id: "Tidak ada pegawai yang lulus ujian" },
      { key: "d", id: "Semua pegawai mengikuti pelatihan" },
    ]),
    correctOptionId: "b",
    explanation: rich(
      p("Premis hanya menjamin “sebagian” yang naik gaji ikut pelatihan, sehingga kesimpulan yang valid adalah kemungkinan (b)."),
    ),
  }),
  q({
    id: "q-tiu-10",
    type: "fill-blank",
    testTypeId: "tt-skd",
    subtestId: "st-tiu",
    difficulty: "medium",
    topics: ["Numerik Isian"],
    tags: ["isian", "pecahan"],
    prompt: rich(p("Isilah titik-titik berikut.")),
    template: rich(
      p("Nilai dari " + m("\\frac{3}{4} + \\frac{2}{5}") + " = {{b1}} (tuliskan dalam bentuk pecahan, misal 23/20)"),
    ),
    blanks: [
      {
        id: "b1",
        input: "text",
        mode: "advanced",
        accepted: ["23/20", "23 / 20", "1,15", "1.15"],
        caseSensitive: false,
        ignoreWhitespace: true,
      },
    ],
    partialScoring: false,
    explanation: rich(
      p("Samakan penyebut:") + mb("\\frac{3}{4} + \\frac{2}{5} = \\frac{15}{20} + \\frac{8}{20} = \\frac{23}{20} = 1{,}15"),
    ),
  }),
];

/* ============================== TKP ============================== */

const TKP: Question[] = [
  q({
    id: "q-tkp-01",
    type: "weighted-choice",
    testTypeId: "tt-skd",
    subtestId: "st-tkp",
    difficulty: "medium",
    topics: ["Pelayanan Publik"],
    tags: ["tkp", "pelayanan"],
    prompt: rich(
      p("Seorang warga datang ke kantor Anda menjelang waktu pulang dengan berkas yang tidak lengkap. Sikap Anda …"),
    ),
    options: options([
      { key: "a", id: "Menjelaskan persyaratan yang kurang dan memberi tahu jam pelayanan esok hari", weight: 5 },
      { key: "b", id: "Meminta warga datang kembali tanpa penjelasan", weight: 1 },
      { key: "c", id: "Memproses berkas apa adanya agar cepat selesai", weight: 3 },
      { key: "d", id: "Meminta warga menunggu hingga besok tanpa kepastian", weight: 2 },
      { key: "e", id: "Menawarkan bantuan menghubungi bagian terkait lain hari", weight: 4 },
    ]),
    mode: "weight",
    targetOptionId: "a",
    minWeight: 1,
    maxWeight: 5,
    explanation: rich(
      p("Bobot tertinggi ada pada opsi yang tetap ramah, memberi solusi konkret, dan menghargai waktu warga."),
    ),
  }),
  q({
    id: "q-tkp-02",
    type: "weighted-choice",
    testTypeId: "tt-skd",
    subtestId: "st-tkp",
    difficulty: "medium",
    topics: ["Integritas"],
    tags: ["integritas", "gratifikasi"],
    prompt: rich(
      p("Rekan kerja memberikan hadiah agar Anda memprioritaskan permohonannya. Anda …"),
    ),
    options: options([
      { key: "a", id: "Menerima karena nilainya kecil", weight: 1 },
      { key: "b", id: "Menolak dengan sopan dan menjelaskan aturan antigratifikasi", weight: 5 },
      { key: "c", id: "Menerima lalu melaporkan ke atasan tanpa sepengetahuan rekan", weight: 3 },
      { key: "d", id: "Mengabaikan pesan tersebut", weight: 2 },
      { key: "e", id: "Melaporkan ke unit kepatuhan sesuai prosedur", weight: 4 },
    ]),
    mode: "weight",
    targetOptionId: "b",
    minWeight: 1,
    maxWeight: 5,
    explanation: rich(p("Menolak dengan tegas namun santun adalah perilaku berintegritas tertinggi.")),
  }),
  q({
    id: "q-tkp-03",
    type: "weighted-choice",
    testTypeId: "tt-skd",
    subtestId: "st-tkp",
    difficulty: "hard",
    topics: ["Kerja Sama Tim"],
    tags: ["kolaborasi"],
    prompt: rich(p("Anggota tim Anda beberapa kali terlambat menyelesaikan tugas. Anda …")),
    options: options([
      { key: "a", id: "Membicarakan secara pribadi dan menawarkan bantuan", weight: 5 },
      { key: "b", id: "Melaporkan langsung ke atasan agar diberi sanksi", weight: 2 },
      { key: "c", id: "Menyelesaikan tugasnya sendiri agar target tercapai", weight: 3 },
      { key: "d", id: "Membiarkan karena bukan tanggung jawab saya", weight: 1 },
      { key: "e", id: "Mengingatkan di grup kerja agar semua tahu", weight: 2 },
    ]),
    mode: "weight",
    targetOptionId: "a",
    minWeight: 1,
    maxWeight: 5,
    explanation: rich(p("Pendekatan personal dan solutif menjaga hubungan kerja sekaligus menyelesaikan masalah.")),
  }),
  q({
    id: "q-tkp-04",
    type: "weighted-choice",
    testTypeId: "tt-skd",
    subtestId: "st-tkp",
    difficulty: "medium",
    topics: ["Teknologi & Adaptasi"],
    tags: ["adaptasi", "teknologi"],
    prompt: rich(p("Instansi Anda baru saja menggunakan sistem digital baru. Sikap Anda …")),
    options: options([
      { key: "a", id: "Mempelajari panduan dan membantu rekan yang kesulitan", weight: 5 },
      { key: "b", id: "Menunggu pelatihan resmi dari kantor", weight: 3 },
      { key: "c", id: "Tetap memakai cara lama yang sudah terbukti", weight: 1 },
      { key: "d", id: "Mencoba pelan-pelan bila ada waktu luang", weight: 3 },
    ]),
    mode: "weight",
    targetOptionId: "a",
    minWeight: 1,
    maxWeight: 5,
    explanation: rich(p("Inisiatif belajar dan berbagi pengetahuan menunjukkan kemampuan beradaptasi tertinggi.")),
  }),
  q({
    id: "q-tkp-05",
    type: "weighted-choice",
    testTypeId: "tt-skd",
    subtestId: "st-tkp",
    difficulty: "medium",
    topics: ["Etika Sosial"],
    tags: ["sosial", "masyarakat"],
    prompt: rich(p("Tetangga mengadakan hajatan hingga larut malam di dekat rumah Anda. Anda …")),
    options: options([
      { key: "a", id: "Membiarkannya karena itu hak mereka", weight: 3 },
      { key: "b", id: "Menegur dengan santun dan menyampaikan dampaknya", weight: 5 },
      { key: "c", id: "Menghubungi aparat tanpa bicara langsung", weight: 2 },
      { key: "d", id: "Memasang pengeras suara sendiri sebagai balasan", weight: 1 },
    ]),
    mode: "weight",
    targetOptionId: "b",
    minWeight: 1,
    maxWeight: 5,
    explanation: rich(p("Musyawarah dan komunikasi santun mencerminkan kecerdasan sosial yang baik.")),
  }),
  q({
    id: "q-tkp-06",
    type: "weighted-choice",
    testTypeId: "tt-skd",
    subtestId: "st-tkp",
    difficulty: "hard",
    topics: ["Profesionalisme"],
    tags: ["profesional", "target"],
    prompt: rich(p("Target kerja bulan ini tidak tercapai karena kendala dari pihak luar. Anda …")),
    options: options([
      { key: "a", id: "Menyusun laporan evaluasi beserta rencana perbaikan", weight: 5 },
      { key: "b", id: "Menyalahkan pihak luar dalam laporan", weight: 1 },
      { key: "c", id: "Menunggu instruksi atasan", weight: 2 },
      { key: "d", id: "Menambah jam kerja tanpa evaluasi", weight: 3 },
    ]),
    mode: "weight",
    targetOptionId: "a",
    minWeight: 1,
    maxWeight: 5,
    explanation: rich(p("Evaluasi disertai rencana perbaikan menunjukkan akuntabilitas profesional.")),
  }),
];

export const SKD_QUESTIONS: Question[] = [...TWK, ...TIU, ...TKP];
export const TWK_QUESTION_IDS = TWK.map((item) => item.id);
export const TIU_QUESTION_IDS = TIU.map((item) => item.id);
export const TKP_QUESTION_IDS = TKP.map((item) => item.id);
