import type { Question } from "@/types";
import { bi, m, options, p, q, rich } from "../helpers";

/* ========================= PENGETAHUAN UMUM ========================= */

const PU: Question[] = [
  q({
    id: "q-umum-pu-01",
    type: "multiple-choice",
    testTypeId: "tt-umum",
    subtestId: "st-umum-pu",
    difficulty: "easy",
    topics: ["Teknologi"],
    tags: ["teknologi", "internet"],
    prompt: rich(p("Protokol standar yang digunakan untuk mengirimkan halaman web adalah …")),
    options: options([
      { key: "a", id: "FTP" },
      { key: "b", id: "HTTPS" },
      { key: "c", id: "SMTP" },
      { key: "d", id: "SSH" },
    ]),
    correctOptionId: "b",
    explanation: rich(p("HTTPS (HTTP Secure) adalah protokol lapisan aplikasi untuk mengirim halaman web secara terenkripsi.")),
  }),
  q({
    id: "q-umum-pu-02",
    type: "multiple-answer",
    testTypeId: "tt-umum",
    subtestId: "st-umum-pu",
    difficulty: "medium",
    topics: ["Lingkungan"],
    tags: ["lingkungan", "energi"],
    prompt: rich(p("Pilih <strong>semua</strong> sumber energi terbarukan berikut ini.")),
    options: options([
      { key: "a", id: "Angin" },
      { key: "b", id: "Batu bara" },
      { key: "c", id: "Matahari" },
      { key: "d", id: "Gas alam" },
      { key: "e", id: "Panas bumi" },
    ]),
    correctOptionIds: ["a", "c", "e"],
    partialScoring: true,
    penalizeWrong: true,
    explanation: rich(p("Angin, matahari, dan panas bumi termasuk energi terbarukan; batu bara dan gas alam adalah energi fosil.")),
  }),
  q({
    id: "q-umum-pu-03",
    type: "true-false",
    testTypeId: "tt-umum",
    subtestId: "st-umum-pu",
    difficulty: "easy",
    topics: ["Kesehatan"],
    tags: ["kesehatan", "benar-salah"],
    prompt: rich(p("Air minum yang mendidih selama satu menit dapat membunuh sebagian besar kuman penyebab diare.")),
    variant: "true-false",
    correct: true,
    explanation: rich(p("Mendidihkan air adalah cara paling sederhana dan efektif membunuh patogen berbahaya.")),
  }),
  q({
    id: "q-umum-pu-04",
    type: "matching",
    testTypeId: "tt-umum",
    subtestId: "st-umum-pu",
    difficulty: "medium",
    topics: ["Organisasi"],
    tags: ["menjodohkan", "lembaga"],
    prompt: rich(p("Pasangkan setiap lembaga dengan fungsi utamanya.")),
    pairs: [
      { id: "p1", left: rich(p("WHO")), right: rich(p("Kesehatan dunia")) },
      { id: "p2", left: rich(p("UNESCO")), right: rich(p("Pendidikan & kebudayaan")) },
      { id: "p3", left: rich(p("IMF")), right: rich(p("Stabilitas keuangan global")) },
      { id: "p4", left: rich(p("WTO")), right: rich(p("Perdagangan internasional")) },
    ],
    distractors: [rich(p("Keamanan maritim"))],
    partialScoring: true,
    explanation: rich(p("WHO–kesehatan, UNESCO–pendidikan/kebudayaan, IMF–keuangan, WTO–perdagangan.")),
  }),
  q({
    id: "q-umum-pu-05",
    type: "ordering",
    testTypeId: "tt-umum",
    subtestId: "st-umum-pu",
    difficulty: "hard",
    topics: ["Tata Surya"],
    tags: ["mengurutkan", "astronomi"],
    prompt: rich(p("Urutkan planet berikut dari yang <strong>terdekat</strong> ke matahari.")),
    items: [
      { id: "i1", content: rich(p("Bumi")) },
      { id: "i2", content: rich(p("Merkurius")) },
      { id: "i3", content: rich(p("Mars")) },
      { id: "i4", content: rich(p("Venus")) },
    ],
    correctOrder: ["i2", "i4", "i1", "i3"],
    partialScoring: true,
    explanation: rich(p("Urutan yang benar: Merkurius → Venus → Bumi → Mars.")),
  }),
  q({
    id: "q-umum-pu-06",
    type: "fill-blank",
    testTypeId: "tt-umum",
    subtestId: "st-umum-pu",
    difficulty: "medium",
    topics: ["Sejarah"],
    tags: ["isian", "sejarah"],
    prompt: rich(p("Lengkapi dua pernyataan berikut.")),
    template: rich(
      p("Proklamasi Kemerdekaan Indonesia dibacakan pada tanggal {{b1}} tahun {{b2}}."),
    ),
    blanks: [
      {
        id: "b1",
        label: "Tanggal",
        input: "text",
        mode: "advanced",
        accepted: ["17 Agustus", "17-8", "17/8", "17 Agustus 1945"],
        caseSensitive: false,
        ignoreWhitespace: true,
      },
      {
        id: "b2",
        label: "Tahun",
        input: "dropdown",
        mode: "exact",
        accepted: ["1945"],
        choices: ["1943", "1945", "1948", "1950"],
      },
    ],
    partialScoring: true,
    explanation: rich(p("Proklamasi dibacakan Ir. Soekarno pada 17 Agustus 1945 di Jalan Pegangsaan Timur 56, Jakarta.")),
  }),
];

/* =========================== LOGIKA =========================== */

const LOGIKA: Question[] = [
  q({
    id: "q-umum-log-01",
    type: "multiple-choice",
    testTypeId: "tt-umum",
    subtestId: "st-umum-logika",
    difficulty: "medium",
    topics: ["Logika"],
    tags: ["logika", "silogisme"],
    prompt: rich(p("Jika tidak ada burung yang tidak bisa terbang, maka …")),
    options: options([
      { key: "a", id: "Semua burung bisa terbang" },
      { key: "b", id: "Sebagian burung tidak bisa terbang" },
      { key: "c", id: "Hanya burung liar yang bisa terbang" },
      { key: "d", id: "Tidak ada kesimpulan" },
    ]),
    correctOptionId: "a",
    explanation: rich(p("“Tidak ada … yang tidak” = ganda negasi = semua burung bisa terbang.")),
  }),
  q({
    id: "q-umum-log-02",
    type: "multiple-choice",
    testTypeId: "tt-umum",
    subtestId: "st-umum-logika",
    difficulty: "hard",
    topics: ["Numerik"],
    tags: ["numerik", "persen"],
    prompt: rich(p("Harga sebuah barang naik 25% lalu turun 20%. Harga akhir dibanding harga awal …")),
    options: options([
      { key: "a", id: "Naik 5%" },
      { key: "b", id: "Turun 5%" },
      { key: "c", id: "Tetap sama" },
      { key: "d", id: "Naik 2,5%" },
    ]),
    correctOptionId: "c",
    explanation: rich(p("Pengali: " + m("1{,}25 \\times 0{,}80 = 1{,}00") + " → harga kembali ke nilai awal.")),
  }),
  q({
    id: "q-umum-log-03",
    type: "fill-blank",
    testTypeId: "tt-umum",
    subtestId: "st-umum-logika",
    difficulty: "medium",
    topics: ["Numerik"],
    tags: ["isian", "toleransi"],
    prompt: rich(p("Isi dengan angka. Toleransi jawaban 0,5.")),
    template: rich(p("Akar pangkat dua dari 50 adalah sekitar {{b1}}.")),
    blanks: [
      {
        id: "b1",
        input: "text",
        mode: "numeric",
        accepted: ["7.07"],
        tolerance: 0.5,
      },
    ],
    partialScoring: false,
    explanation: rich(p("Nilai " + m("\\sqrt{50} \\approx 7{,}071") + ", sehingga jawaban antara 6,57–7,57 diterima.")),
  }),
  q({
    id: "q-umum-log-04",
    type: "multiple-choice",
    testTypeId: "tt-umum",
    subtestId: "st-umum-logika",
    difficulty: "hard",
    topics: ["Logika Diagram"],
    tags: ["logika", "himpunan"],
    prompt: rich(
      p("Dalam sebuah kelas, 20 siswa suka matematika, 15 suka fisika, dan 8 suka keduanya. Jumlah siswa di kelas tersebut adalah …")),
    options: options([
      { key: "a", id: "27" },
      { key: "b", id: "35" },
      { key: "c", id: "43" },
      { key: "d", id: "23" },
    ]),
    correctOptionId: "a",
    explanation: rich(
      p("Gunakan prinsip inklusi-eksklusi:") + m("20 + 15 - 8 = 27")),
  }),
  q({
    id: "q-umum-log-05",
    type: "true-false",
    testTypeId: "tt-umum",
    subtestId: "st-umum-logika",
    difficulty: "easy",
    topics: ["Logika"],
    tags: ["logika", "ya-tidak"],
    prompt: rich(p("Apakah pernyataan ini benar: “Semua bilangan prima adalah bilangan ganjil”.")),
    variant: "yes-no",
    correct: false,
    explanation: rich(p("Angka 2 adalah bilangan prima sekaligus genap, sehingga pernyataan itu salah.")),
  }),
  q({
    id: "q-umum-log-06",
    type: "multiple-choice",
    testTypeId: "tt-umum",
    subtestId: "st-umum-logika",
    difficulty: "medium",
    topics: ["Pola Gambar"],
    tags: ["logika", "pola"],
    prompt: rich(p("Jika 2 = 6, 3 = 12, 4 = 20, maka 6 = …")),
    options: options([
      { key: "a", id: "30" },
      { key: "b", id: "36" },
      { key: "c", id: "42" },
      { key: "d", id: "48" },
    ]),
    correctOptionId: "c",
    explanation: rich(p("Pola " + m("n(n+1)") + ": " + m("2 \\cdot 3 = 6") + ", " + m("3 \\cdot 4 = 12") + ", " + m("6 \\cdot 7 = 42") + ".")),
  }),
];

/* ============================= ESAI ============================= */

const ESAI: Question[] = [
  q({
    id: "q-umum-esai-01",
    type: "essay",
    testTypeId: "tt-umum",
    subtestId: "st-umum-esai",
    difficulty: "medium",
    topics: ["Opini"],
    tags: ["esai", "pendek"],
    prompt: rich(
      p("Jelaskan dalam 50–100 kata mengapa literasi digital penting bagi pelajar Indonesia saat ini."),
    ),
    length: "short",
    maxScore: 10,
    keywords: [
      { term: "hoaks", points: 2 },
      { term: "sumber", points: 2 },
      { term: "privasi", points: 2 },
      { term: "etika", points: 2 },
      { term: "verifikasi", points: 2 },
    ],
    rubric: [
      { id: "r1", label: bi("Kesesuaian isi", "Content relevance"), maxScore: 4 },
      { id: "r2", label: bi("Struktur & kejelasan", "Structure & clarity"), maxScore: 3 },
      { id: "r3", label: bi("Tata bahasa", "Grammar"), maxScore: 3 },
    ],
    minWords: 50,
    manualGrading: true,
    explanation: rich(p("Jawaban ideal memuat verifikasi sumber, risiko hoaks, privasi data, dan etika bermedia.")),
  }),
  q({
    id: "q-umum-esai-02",
    type: "essay",
    testTypeId: "tt-umum",
    subtestId: "st-umum-esai",
    difficulty: "hard",
    topics: ["Analisis"],
    tags: ["esai", "panjang"],
    prompt: rich(
      p("Analisislah dampak kerja jarak jauh terhadap produktivitas tim. Sertakan minimal dua argumen pendukung dan satu argumen penyeimbang."),
    ),
    length: "long",
    maxScore: 20,
    keywords: [
      { term: "fleksibilitas", points: 3 },
      { term: "komunikasi", points: 3 },
      { term: "koordinasi", points: 3 },
      { term: "evaluasi", points: 3 },
    ],
    rubric: [
      { id: "r1", label: bi("Kedalaman analisis", "Depth of analysis"), maxScore: 8 },
      { id: "r2", label: bi("Argumen pendukung & penyeimbang", "Supporting & counter arguments"), maxScore: 6 },
      { id: "r3", label: bi("Sistematika penulisan", "Writing structure"), maxScore: 6 },
    ],
    minWords: 120,
    manualGrading: true,
    explanation: rich(p("Skor penuh bila memuat argumen dua sisi, data/contoh konkret, dan kesimpulan yang utuh.")),
  }),
];

export const UMUM_QUESTIONS: Question[] = [...PU, ...LOGIKA, ...ESAI];
export const UMUM_PU_IDS = PU.map((item) => item.id);
export const UMUM_LOGIKA_IDS = LOGIKA.map((item) => item.id);
export const UMUM_ESAI_IDS = ESAI.map((item) => item.id);
